"""Managed runtime materialization."""

import filecmp
import os
import shutil
from dataclasses import dataclass, field
from pathlib import Path

from dotagents.assets import asset_root
from dotagents.errors import DotagentsError
from dotagents.lockfile import LockedAsset, RuntimeLock, read_lock, sha256_file, write_lock
from dotagents.manifest import (
  Manifest,
  SyncEntry,
  load_manifest,
  selected_entries,
  selected_providers,
)
from dotagents.version import package_version


@dataclass
class OperationLog:
  dry_run: bool = False
  lines: list[str] = field(default_factory=list)
  pending_removals: set[Path] = field(default_factory=set)

  def add(self, message: str) -> None:
    self.lines.append(message)


@dataclass(frozen=True)
class RuntimeContext:
  repo_root: Path
  runtime_dir: Path
  asset_root: Path
  manifest: Manifest
  providers: tuple[str, ...]


@dataclass(frozen=True)
class RuntimeVersionDrift:
  runtime_version: str
  package_version: str

  def update_guidance(self) -> str:
    return (
      f"runtime was generated by dotagents {self.runtime_version} but installed "
      f"package is {self.package_version}. Run: uv run dotagents update"
    )


def version_drift(runtime_lock: RuntimeLock) -> RuntimeVersionDrift | None:
  installed_version = package_version()
  if runtime_lock.version == installed_version:
    return None
  return RuntimeVersionDrift(
    runtime_version=runtime_lock.version,
    package_version=installed_version,
  )


def build_context(repo_root: Path, requested_providers: tuple[str, ...] = ()) -> RuntimeContext:
  root = repo_root.resolve()
  assets = asset_root()
  manifest = load_manifest(assets)
  configured = requested_providers or configured_providers(root, manifest)
  providers = selected_providers(manifest, configured)
  return RuntimeContext(
    repo_root=root,
    runtime_dir=root / ".agents",
    asset_root=assets,
    manifest=manifest,
    providers=providers,
  )


def configured_providers(repo_root: Path, manifest: Manifest) -> tuple[str, ...]:
  lock_path = repo_root / ".agents" / "dotagents.lock"
  if not lock_path.exists():
    return manifest.providers
  return read_lock(lock_path).providers


def init_runtime(
  repo_root: Path, providers: tuple[str, ...], dry_run: bool = False
) -> OperationLog:
  return sync_runtime(build_context(repo_root, providers), dry_run=dry_run)


def sync_existing(repo_root: Path, dry_run: bool = False) -> OperationLog:
  runtime_context = build_context(repo_root)
  lock_path = runtime_context.runtime_dir / "dotagents.lock"
  if lock_path.exists():
    drift = version_drift(read_lock(lock_path))
    if drift:
      raise DotagentsError(drift.update_guidance())
  operation_log = sync_runtime(runtime_context, dry_run=dry_run)
  operation_log.lines.append("sync used current dotagents package assets")
  return operation_log


def update_existing(repo_root: Path, dry_run: bool = False) -> OperationLog:
  runtime_context = build_context(repo_root)
  lock_path = runtime_context.runtime_dir / "dotagents.lock"
  previous_version = read_lock(lock_path).version if lock_path.exists() else None
  operation_log = sync_runtime(runtime_context, dry_run=dry_run)
  installed_version = package_version()
  if previous_version is None:
    operation_log.lines.append(f"update created runtime with dotagents {installed_version}")
  elif previous_version == installed_version:
    operation_log.lines.append(f"runtime at {installed_version}; refreshed managed files")
  else:
    operation_log.lines.append(f"updated runtime: {previous_version} -> {installed_version}")
  return operation_log


def uninstall_existing(repo_root: Path, dry_run: bool = False) -> OperationLog:
  root = repo_root.resolve()
  runtime_dir = root / ".agents"
  lock_path = runtime_dir / "dotagents.lock"
  if not lock_path.exists():
    raise DotagentsError("cannot uninstall: missing .agents/dotagents.lock")

  runtime_lock = read_lock(lock_path)
  operation_log = OperationLog(dry_run=dry_run)
  prune_candidates: set[Path] = set()

  for destination, source in uninstall_links(
    root, runtime_dir, runtime_lock, operation_log
  ).items():
    remove_expected_link(root, destination, source, operation_log)
    collect_parents(root, destination, prune_candidates)

  remove_generated_rules(root, operation_log)
  collect_parents(root, root / ".rules", prune_candidates)

  for asset in sorted(runtime_lock.assets, key=lambda item: item.destination, reverse=True):
    path = root / asset.destination
    remove_locked_asset(root, path, asset.sha256, operation_log)
    collect_parents(root, path, prune_candidates)

  remove_lockfile(root, lock_path, operation_log)
  collect_parents(root, lock_path, prune_candidates)
  prune_empty_dirs(root, prune_candidates, operation_log)
  operation_log.add(
    "would uninstall dotagents runtime"
    if operation_log.dry_run
    else "uninstalled dotagents runtime"
  )
  return operation_log


def add_provider(repo_root: Path, provider: str, dry_run: bool = False) -> OperationLog:
  root = repo_root.resolve()
  lock_path = root / ".agents" / "dotagents.lock"
  if not lock_path.exists():
    raise DotagentsError(
      "cannot add provider: missing .agents/dotagents.lock. Run: uv run dotagents init"
    )
  current_lock = read_lock(lock_path)
  drift = version_drift(current_lock)
  if drift:
    raise DotagentsError(drift.update_guidance())
  if provider in current_lock.providers:
    operation_log = OperationLog(dry_run=dry_run)
    operation_log.add(f"provider already configured: {provider}")
    return operation_log
  new_providers = (*current_lock.providers, provider)
  return sync_runtime(build_context(root, new_providers), dry_run=dry_run)


def remove_provider(repo_root: Path, provider: str, dry_run: bool = False) -> OperationLog:
  root = repo_root.resolve()
  runtime_dir = root / ".agents"
  lock_path = runtime_dir / "dotagents.lock"
  if not lock_path.exists():
    raise DotagentsError("cannot remove provider: missing .agents/dotagents.lock")

  current_lock = read_lock(lock_path)
  drift = version_drift(current_lock)
  if drift:
    raise DotagentsError(drift.update_guidance())
  if provider not in current_lock.providers:
    raise DotagentsError(f"provider not configured: {provider}")

  try:
    assets = asset_root()
    manifest = load_manifest(assets)
  except DotagentsError:
    manifest = None

  remaining_providers = tuple(p for p in current_lock.providers if p != provider)
  operation_log = OperationLog(dry_run=dry_run)
  prune_candidates: set[Path] = set()

  if manifest is None:
    operation_log.add(
      "warning: cannot load manifest; expected symlinks not removed — remove manually"
    )
  elif provider not in manifest.provider_sync:
    operation_log.add(
      f"warning: provider {provider!r} not in current manifest; symlinks not removed — remove manually"
    )
  else:
    for entry in manifest.provider_sync[provider]:
      source = (
        root / ".rules" if entry.source == ".rules" else runtime_destination(runtime_dir, entry)
      )
      destination = root / entry.destination
      remove_expected_link(root, destination, source, operation_log)
      collect_parents(root, destination, prune_candidates)

  provider_prefix = f".agents/providers/{provider}/"
  skipped_assets: list[LockedAsset] = []
  for asset in sorted(
    (a for a in current_lock.assets if a.destination.startswith(provider_prefix)),
    key=lambda a: a.destination,
    reverse=True,
  ):
    path = root / asset.destination
    removed = remove_locked_asset(root, path, asset.sha256, operation_log)
    if not removed:
      skipped_assets.append(asset)
    collect_parents(root, path, prune_candidates)

  prune_empty_dirs(root, prune_candidates, operation_log)

  if not dry_run:
    remaining_assets = [
      a for a in current_lock.assets if not a.destination.startswith(provider_prefix)
    ] + skipped_assets
    write_lock(lock_path, remaining_providers, remaining_assets)
    operation_log.add(f"removed provider: {provider}")
  else:
    operation_log.add(f"would remove provider: {provider}")

  return operation_log


def sync_runtime(runtime_context: RuntimeContext, dry_run: bool = False) -> OperationLog:
  operation_log = OperationLog(dry_run=dry_run)
  locked_assets: list[LockedAsset] = []

  ensure_dir(runtime_context.repo_root, runtime_context.runtime_dir, operation_log)
  copy_file(
    runtime_context.repo_root,
    runtime_context.asset_root / "agents.toml",
    runtime_context.runtime_dir / "agents.toml",
    operation_log,
  )
  locked_assets.append(
    LockedAsset(
      "agents.toml",
      relative(runtime_context.repo_root, runtime_context.runtime_dir / "agents.toml"),
      sha256_file(runtime_context.asset_root / "agents.toml"),
    )
  )

  for entry in selected_entries(runtime_context.manifest, runtime_context.providers):
    if entry.source == ".rules":
      continue
    source = runtime_context.asset_root / entry.source
    destination = runtime_destination(runtime_context.runtime_dir, entry)
    copy_path(runtime_context.repo_root, source, destination, operation_log)
    locked_assets.extend(lock_entries(runtime_context.repo_root, source, destination, entry.source))

  render_rules(runtime_context, operation_log)

  for entry in selected_entries(runtime_context.manifest, runtime_context.providers):
    source = (
      runtime_context.repo_root / ".rules"
      if entry.source == ".rules"
      else runtime_destination(runtime_context.runtime_dir, entry)
    )
    link_path(
      runtime_context.repo_root,
      source,
      runtime_context.repo_root / entry.destination,
      operation_log,
    )

  if dry_run:
    operation_log.add("would write .agents/dotagents.lock")
  else:
    write_lock(
      runtime_context.runtime_dir / "dotagents.lock",
      runtime_context.providers,
      unique_locked_assets(locked_assets),
    )
    operation_log.add("wrote .agents/dotagents.lock")

  return operation_log


def runtime_destination(runtime_dir: Path, entry: SyncEntry) -> Path:
  source = Path(entry.source)
  first = source.parts[0]
  if first in {"scripts", "skills"}:
    return runtime_dir / source
  if entry.provider and first == entry.provider:
    suffix = Path(*source.parts[1:]) if len(source.parts) > 1 else Path()
    return runtime_dir / "providers" / entry.provider / suffix
  raise DotagentsError(f"unsupported manifest source root: {entry.source}")


def expected_links(runtime_context: RuntimeContext) -> dict[Path, Path]:
  links: dict[Path, Path] = {}
  for entry in selected_entries(runtime_context.manifest, runtime_context.providers):
    source = (
      runtime_context.repo_root / ".rules"
      if entry.source == ".rules"
      else runtime_destination(runtime_context.runtime_dir, entry)
    )
    links[runtime_context.repo_root / entry.destination] = source
  return links


def uninstall_links(
  repo_root: Path, runtime_dir: Path, runtime_lock: RuntimeLock, operation_log: OperationLog
) -> dict[Path, Path]:
  try:
    assets = asset_root()
    manifest = load_manifest(assets)
  except DotagentsError:
    operation_log.add(
      "warning: cannot load manifest; expected symlinks not removed — remove manually"
    )
    return {}

  available_providers = tuple(
    provider for provider in runtime_lock.providers if provider in manifest.providers
  )
  runtime_context = RuntimeContext(
    repo_root=repo_root,
    runtime_dir=runtime_dir,
    asset_root=assets,
    manifest=manifest,
    providers=available_providers,
  )
  return expected_links(runtime_context)


def render_rules(runtime_context: RuntimeContext, operation_log: OperationLog) -> None:
  shared_rules = runtime_context.asset_root / "rules" / "rules.md"
  try:
    shared = shared_rules.read_text(encoding="utf-8").rstrip()
  except OSError as exc:
    raise DotagentsError(f"cannot read bundled rules file: {shared_rules}") from exc
  chunks = ["<!-- Shared agent rules from dotagents package rules/rules.md -->", "", shared]
  local = runtime_context.repo_root / ".rules.local"
  if local.exists():
    chunks.extend(
      [
        "",
        "",
        "<!-- Local repo rules from .rules.local -->",
        "",
        local.read_text(encoding="utf-8").rstrip(),
      ]
    )
  write_text(
    runtime_context.repo_root,
    runtime_context.repo_root / ".rules",
    "\n".join(chunks) + "\n",
    operation_log,
  )


def lock_entries(
  repo_root: Path, source: Path, destination: Path, source_name: str
) -> list[LockedAsset]:
  if source.is_file():
    return [LockedAsset(source_name, relative(repo_root, destination), sha256_file(source))]

  entries: list[LockedAsset] = []
  for path in sorted(source.rglob("*")):
    if path.is_file():
      relative_path = path.relative_to(source)
      entries.append(
        LockedAsset(
          str(Path(source_name) / relative_path),
          relative(repo_root, destination / relative_path),
          sha256_file(path),
        )
      )
  return entries


def unique_locked_assets(locked_assets: list[LockedAsset]) -> list[LockedAsset]:
  unique: dict[tuple[str, str], LockedAsset] = {}
  for asset in locked_assets:
    unique[(asset.source, asset.destination)] = asset
  return list(unique.values())


def copy_path(
  repo_root: Path, source: Path, destination: Path, operation_log: OperationLog
) -> None:
  if source.is_dir():
    for path in sorted(source.rglob("*")):
      if path.is_file():
        copy_file(repo_root, path, destination / path.relative_to(source), operation_log)
    return
  copy_file(repo_root, source, destination, operation_log)


def copy_file(
  repo_root: Path, source: Path, destination: Path, operation_log: OperationLog
) -> None:
  if (
    destination.exists()
    and destination.is_file()
    and filecmp.cmp(source, destination, shallow=False)
  ):
    operation_log.add(f"ok {relative(repo_root, destination)}")
    return
  if destination.exists() and destination.is_symlink():
    raise DotagentsError(
      f"refusing to replace symlink with managed file: {relative(repo_root, destination)}"
    )
  if operation_log.dry_run:
    operation_log.add(f"would copy {relative(repo_root, destination)}")
    return
  destination.parent.mkdir(parents=True, exist_ok=True)
  shutil.copy2(source, destination)
  operation_log.add(f"copied {relative(repo_root, destination)}")


def write_text(
  repo_root: Path, destination: Path, content: str, operation_log: OperationLog
) -> None:
  if (
    destination.exists()
    and destination.is_file()
    and destination.read_text(encoding="utf-8") == content
  ):
    operation_log.add(f"ok {relative(repo_root, destination)}")
    return
  if destination.exists() and destination.is_symlink():
    raise DotagentsError(
      f"refusing to replace symlink with managed file: {relative(repo_root, destination)}"
    )
  if operation_log.dry_run:
    operation_log.add(f"would write {relative(repo_root, destination)}")
    return
  destination.write_text(content, encoding="utf-8")
  operation_log.add(f"wrote {relative(repo_root, destination)}")


def link_path(
  repo_root: Path, source: Path, destination: Path, operation_log: OperationLog
) -> None:
  if destination.exists() and not destination.is_symlink():
    raise DotagentsError(
      f"refusing to replace existing non-symlink: {relative(repo_root, destination)}"
    )

  target = os.path.relpath(source, destination.parent)
  if destination.is_symlink() and os.readlink(destination) == target:
    operation_log.add(f"ok {relative(repo_root, destination)}")
    return

  if operation_log.dry_run:
    operation_log.add(f"would link {relative(repo_root, destination)} -> {target}")
    return

  destination.parent.mkdir(parents=True, exist_ok=True)
  if destination.exists() or destination.is_symlink():
    destination.unlink()
  destination.symlink_to(target)
  operation_log.add(f"linked {relative(repo_root, destination)} -> {target}")


def ensure_dir(repo_root: Path, path: Path, operation_log: OperationLog) -> None:
  if path.exists():
    if not path.is_dir():
      raise DotagentsError(f"expected directory: {relative(repo_root, path)}")
    return
  if operation_log.dry_run:
    operation_log.add(f"would create {relative(repo_root, path)}")
    return
  path.mkdir(parents=True)
  operation_log.add(f"created {relative(repo_root, path)}")


def remove_expected_link(
  repo_root: Path, destination: Path, expected_source: Path, operation_log: OperationLog
) -> None:
  display = relative(repo_root, destination)
  if not destination.exists() and not destination.is_symlink():
    operation_log.add(f"missing {display}")
    return
  if not destination.is_symlink():
    operation_log.add(f"skip user-owned {display}; remove manually after verifying")
    return

  expected_target = os.path.relpath(expected_source, destination.parent)
  actual_target = os.readlink(destination)
  if actual_target != expected_target:
    operation_log.add(f"skip unexpected symlink {display}; remove manually after verifying")
    return

  if operation_log.dry_run:
    operation_log.add(f"would remove {display}")
    operation_log.pending_removals.add(destination)
    return
  destination.unlink()
  operation_log.add(f"removed {display}")


def remove_locked_asset(
  repo_root: Path, path: Path, expected_sha256: str, operation_log: OperationLog
) -> bool:
  """Return True if the asset was removed (or would be in dry-run), False if skipped."""
  display = relative(repo_root, path)
  if not path.exists() and not path.is_symlink():
    operation_log.add(f"missing {display}")
    return True
  if path.is_symlink() or not path.is_file():
    operation_log.add(f"skip unexpected {display}; remove manually after verifying")
    return False
  if sha256_file(path) != expected_sha256:
    operation_log.add(f"skip changed {display}; remove manually after verifying")
    return False

  if operation_log.dry_run:
    operation_log.add(f"would remove {display}")
    operation_log.pending_removals.add(path)
    return True
  path.unlink()
  operation_log.add(f"removed {display}")
  return True


def remove_generated_rules(repo_root: Path, operation_log: OperationLog) -> None:
  rules = repo_root / ".rules"
  display = relative(repo_root, rules)
  if not rules.exists() and not rules.is_symlink():
    operation_log.add(f"missing {display}")
    return
  if rules.is_symlink() or not rules.is_file():
    operation_log.add(f"skip unexpected {display}; remove manually after verifying")
    return
  try:
    content = rules.read_text(encoding="utf-8")
  except OSError:
    operation_log.add(f"skip unreadable {display}; remove manually after verifying")
    return
  if "<!-- Shared agent rules from dotagents package rules/rules.md -->" not in content:
    operation_log.add(f"skip user-owned {display}; remove manually after verifying")
    return

  if operation_log.dry_run:
    operation_log.add(f"would remove {display}")
    operation_log.pending_removals.add(rules)
    return
  rules.unlink()
  operation_log.add(f"removed {display}")


def remove_lockfile(repo_root: Path, lock_path: Path, operation_log: OperationLog) -> None:
  display = relative(repo_root, lock_path)
  if not lock_path.exists():
    operation_log.add(f"missing {display}")
    return
  if not lock_path.is_file():
    operation_log.add(f"skip unexpected {display}; remove manually after verifying")
    return

  if operation_log.dry_run:
    operation_log.add(f"would remove {display}")
    operation_log.pending_removals.add(lock_path)
    return
  lock_path.unlink()
  operation_log.add(f"removed {display}")


def collect_parents(repo_root: Path, path: Path, candidates: set[Path]) -> None:
  current = path.parent
  while current != repo_root and repo_root in current.parents:
    candidates.add(current)
    current = current.parent


def prune_empty_dirs(repo_root: Path, candidates: set[Path], operation_log: OperationLog) -> None:
  for path in sorted(candidates, key=lambda item: len(item.parts), reverse=True):
    if path == repo_root or not path.exists() or not path.is_dir():
      continue
    display = relative(repo_root, path)
    if operation_log.dry_run:
      remaining = [child for child in path.iterdir() if child not in operation_log.pending_removals]
      if not remaining:
        operation_log.add(f"would remove empty {display}")
        operation_log.pending_removals.add(path)
    else:
      try:
        next(path.iterdir())
      except StopIteration:
        path.rmdir()
        operation_log.add(f"removed empty {display}")


def relative(base: Path, path: Path) -> str:
  try:
    return os.path.relpath(path, base)
  except ValueError:
    return str(path)
