"""Managed runtime materialization."""

import filecmp
import os
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from dotagents.assets import asset_root
from dotagents.compiler import (
  BuildGroup,
  BuildManifest,
  BuildManifestEntry,
  BuildSource,
  CompilerError,
  parse_mcp_metadata_reference,
  parse_template_source_reference,
  read_build_manifest,
  validate_relative_output_path,
)
from dotagents.errors import DotagentsError
from dotagents.lockfile import (
  LockedAsset,
  LockedLink,
  RuntimeLock,
  read_lock,
  sha256_file,
  write_lock,
)
from dotagents.manifest import (
  Manifest,
  SyncEntry,
  load_manifest,
  selected_entries,
  selected_providers,
)
from dotagents.skillfile import available_skills, resolve_skillfile, skillfile_path
from dotagents.version import package_version

OPT_IN_SKILLS = frozenset({"prek-bootstrap"})
BUILD_MANIFEST_DESTINATION = ".agents/build/manifest.json"


@dataclass
class OperationLog:
  dry_run: bool = False
  lines: list[str] = field(default_factory=list)
  pending_removals: set[Path] = field(default_factory=set)

  def add(self, message: str) -> None:
    self.lines.append(message)


@dataclass(frozen=True)
class RuntimeContext:
  repo_root: Path
  runtime_dir: Path
  asset_root: Path
  manifest: Manifest
  providers: tuple[str, ...]
  skills: tuple[str, ...]


@dataclass(frozen=True)
class RuntimeDrift:
  kind: Literal["version", "manifest"]
  runtime_value: str
  package_value: str

  def update_guidance(self) -> str:
    if self.kind == "version":
      return (
        f"runtime was generated by dotagents {self.runtime_value} but installed "
        f"package is {self.package_value}. Run: uv run dotagents update"
      )
    return "agents.toml manifest changed. Run: uv run dotagents update"


@dataclass(frozen=True)
class CompiledGroupStatus:
  id: str
  status: Literal["ok", "stale", "missing", "invalid"]
  messages: tuple[str, ...] = ()


def check_drift(
  kind: Literal["version", "manifest"], runtime_value: str, package_value: str
) -> RuntimeDrift | None:
  if runtime_value == package_value:
    return None
  return RuntimeDrift(kind=kind, runtime_value=runtime_value, package_value=package_value)


def version_drift(runtime_lock: RuntimeLock) -> RuntimeDrift | None:
  return check_drift("version", runtime_lock.version, package_version())


def compute_manifest_sha256(runtime_context: RuntimeContext) -> str:
  return sha256_file(runtime_context.asset_root / "agents.toml")


def compute_skillfile_sha256(repo_root: Path) -> str | None:
  path = skillfile_path(repo_root)
  return sha256_file(path) if path.exists() else None


def manifest_drift(
  runtime_context: RuntimeContext, runtime_lock: RuntimeLock
) -> RuntimeDrift | None:
  return check_drift(
    "manifest", runtime_lock.manifest_sha256, compute_manifest_sha256(runtime_context)
  )


def default_skills(asset_root: Path) -> tuple[str, ...]:
  return tuple(skill for skill in available_skills(asset_root) if skill not in OPT_IN_SKILLS)


def build_context(repo_root: Path, requested_providers: tuple[str, ...] = ()) -> RuntimeContext:
  root = repo_root.resolve()
  assets = asset_root()
  manifest = load_manifest(assets)
  configured = requested_providers or configured_providers(root, manifest)
  providers = selected_providers(manifest, configured)
  skills = (
    resolve_skillfile(root, assets) if (root / "Skillfile").exists() else default_skills(assets)
  )
  return RuntimeContext(
    repo_root=root,
    runtime_dir=root / ".agents",
    asset_root=assets,
    manifest=manifest,
    providers=providers,
    skills=skills,
  )


def configured_providers(repo_root: Path, manifest: Manifest) -> tuple[str, ...]:
  lock_path = repo_root / ".agents" / "dotagents.lock"
  if not lock_path.exists():
    return manifest.providers
  return read_lock(lock_path).providers


def init_runtime(
  repo_root: Path, providers: tuple[str, ...], dry_run: bool = False, locked: bool = False
) -> OperationLog:
  runtime_context = build_context(repo_root, providers)
  if locked:
    validate_locked_runtime(runtime_context)
  return sync_runtime(runtime_context, dry_run=dry_run, locked=locked)


def sync_existing(repo_root: Path, dry_run: bool = False, locked: bool = False) -> OperationLog:
  runtime_context = build_context(repo_root)
  lock_path = runtime_context.runtime_dir / "dotagents.lock"
  if lock_path.exists():
    runtime_lock = read_lock(lock_path)
    drift = version_drift(runtime_lock)
    if drift:
      raise DotagentsError(drift.update_guidance())
    manifest = manifest_drift(runtime_context, runtime_lock)
    if manifest:
      raise DotagentsError(manifest.update_guidance())
  elif locked:
    raise DotagentsError("cannot sync --locked: missing .agents/dotagents.lock")
  if locked:
    validate_locked_runtime(runtime_context)
  operation_log = sync_runtime(runtime_context, dry_run=dry_run, locked=locked)
  operation_log.lines.append("sync used current dotagents package assets")
  return operation_log


def validate_locked_runtime(runtime_context: RuntimeContext) -> RuntimeLock:
  lock_path = runtime_context.runtime_dir / "dotagents.lock"
  if not lock_path.exists():
    raise DotagentsError("cannot use --locked: missing .agents/dotagents.lock")
  if not skillfile_path(runtime_context.repo_root).exists():
    raise DotagentsError("cannot use --locked: missing Skillfile")
  runtime_lock = read_lock(lock_path)
  drift = version_drift(runtime_lock)
  if drift:
    raise DotagentsError(drift.update_guidance())
  manifest = manifest_drift(runtime_context, runtime_lock)
  if manifest:
    raise DotagentsError(manifest.update_guidance())
  if runtime_lock.skills != runtime_context.skills:
    raise DotagentsError("Skillfile selection differs from lockfile; run: uv run dotagents sync")
  current_skillfile_sha256 = compute_skillfile_sha256(runtime_context.repo_root)
  if runtime_lock.skillfile_sha256 != current_skillfile_sha256:
    raise DotagentsError("Skillfile changed since lockfile; run: uv run dotagents sync")
  return runtime_lock


def update_existing(repo_root: Path, dry_run: bool = False) -> OperationLog:
  runtime_context = build_context(repo_root)
  lock_path = runtime_context.runtime_dir / "dotagents.lock"
  previous_version = read_lock(lock_path).version if lock_path.exists() else None
  operation_log = sync_runtime(runtime_context, dry_run=dry_run)
  installed_version = package_version()
  if previous_version is None:
    operation_log.lines.append(f"update created runtime with dotagents {installed_version}")
  elif previous_version == installed_version:
    operation_log.lines.append(f"runtime at {installed_version}; refreshed managed files")
  else:
    operation_log.lines.append(f"updated runtime: {previous_version} -> {installed_version}")
  return operation_log


def uninstall_existing(repo_root: Path, dry_run: bool = False) -> OperationLog:
  root = repo_root.resolve()
  runtime_dir = root / ".agents"
  lock_path = runtime_dir / "dotagents.lock"
  if not lock_path.exists():
    raise DotagentsError("cannot uninstall: missing .agents/dotagents.lock")

  runtime_lock = read_lock(lock_path)
  operation_log = OperationLog(dry_run=dry_run)
  prune_candidates: set[Path] = set()

  for link in runtime_lock.links:
    destination = root / link.destination
    removed = remove_locked_link(root, destination, link.target, operation_log)
    if link.backup and removed:
      restore_backup(root, root / link.backup, destination, operation_log)
    collect_parents(root, destination, prune_candidates)

  remove_generated_rules(root, operation_log)
  collect_parents(root, root / ".rules", prune_candidates)

  for asset in sorted(runtime_lock.assets, key=lambda item: item.destination, reverse=True):
    path = root / asset.destination
    remove_locked_asset(root, path, asset.sha256, operation_log)
    collect_parents(root, path, prune_candidates)

  remove_lockfile(root, lock_path, operation_log)
  collect_parents(root, lock_path, prune_candidates)
  prune_empty_dirs(root, prune_candidates, operation_log)
  operation_log.add(
    "would uninstall dotagents runtime"
    if operation_log.dry_run
    else "uninstalled dotagents runtime"
  )
  return operation_log


def read_provider_operation_state(
  repo_root: Path, lock_path: Path
) -> tuple[RuntimeLock, RuntimeContext]:
  current_lock = read_lock(lock_path)
  drift = version_drift(current_lock)
  if drift:
    raise DotagentsError(drift.update_guidance())
  runtime_context = build_context(repo_root, current_lock.providers)
  manifest = manifest_drift(runtime_context, current_lock)
  if manifest:
    raise DotagentsError(manifest.update_guidance())
  return current_lock, runtime_context


def add_provider(repo_root: Path, provider: str, dry_run: bool = False) -> OperationLog:
  root = repo_root.resolve()
  lock_path = root / ".agents" / "dotagents.lock"
  if not lock_path.exists():
    raise DotagentsError(
      "cannot add provider: missing .agents/dotagents.lock. Run: uv run dotagents init"
    )
  current_lock, _ = read_provider_operation_state(root, lock_path)
  if provider in current_lock.providers:
    operation_log = OperationLog(dry_run=dry_run)
    operation_log.add(f"provider already configured: {provider}")
    return operation_log
  new_providers = (*current_lock.providers, provider)
  return sync_runtime(build_context(root, new_providers), dry_run=dry_run)


def remove_provider(repo_root: Path, provider: str, dry_run: bool = False) -> OperationLog:
  root = repo_root.resolve()
  runtime_dir = root / ".agents"
  lock_path = runtime_dir / "dotagents.lock"
  if not lock_path.exists():
    raise DotagentsError("cannot remove provider: missing .agents/dotagents.lock")

  current_lock, runtime_context = read_provider_operation_state(root, lock_path)
  if provider not in current_lock.providers:
    raise DotagentsError(f"provider not configured: {provider}")

  remaining_providers = tuple(p for p in current_lock.providers if p != provider)
  operation_log = OperationLog(dry_run=dry_run)
  prune_candidates: set[Path] = set()

  skipped_links: list[LockedLink] = []
  for link in (link for link in current_lock.links if link.provider == provider):
    destination = root / link.destination
    removed = remove_locked_link(root, destination, link.target, operation_log)
    if removed:
      if link.backup:
        restore_backup(root, root / link.backup, destination, operation_log)
    else:
      skipped_links.append(link)
    collect_parents(root, destination, prune_candidates)

  provider_prefix = f".agents/providers/{provider}/"
  skipped_assets: list[LockedAsset] = []
  for asset in sorted(
    (a for a in current_lock.assets if a.destination.startswith(provider_prefix)),
    key=lambda a: a.destination,
    reverse=True,
  ):
    path = root / asset.destination
    removed = remove_locked_asset(root, path, asset.sha256, operation_log)
    if not removed:
      skipped_assets.append(asset)
    collect_parents(root, path, prune_candidates)

  prune_empty_dirs(root, prune_candidates, operation_log)

  if not dry_run:
    remaining_assets = [
      a for a in current_lock.assets if not a.destination.startswith(provider_prefix)
    ] + skipped_assets
    remaining_links = [
      link for link in current_lock.links if link.provider != provider
    ] + skipped_links
    write_lock(
      lock_path,
      compute_manifest_sha256(runtime_context),
      remaining_providers,
      remaining_assets,
      remaining_links,
      skills=current_lock.skills,
      skillfile_sha256=current_lock.skillfile_sha256,
    )
    operation_log.add(f"removed provider: {provider}")
  else:
    operation_log.add(f"would remove provider: {provider}")

  return operation_log


def sync_runtime(
  runtime_context: RuntimeContext, dry_run: bool = False, locked: bool = False
) -> OperationLog:
  operation_log = OperationLog(dry_run=dry_run)
  locked_assets: list[LockedAsset] = []
  locked_links: list[LockedLink] = []
  lock_path = runtime_context.runtime_dir / "dotagents.lock"
  previous_lock = read_lock(lock_path) if lock_path.exists() else None
  compiled_assets = compiled_lock_entries(runtime_context.repo_root, previous_lock)
  validate_compiled_assets_do_not_conflict(runtime_context, compiled_assets)

  ensure_dir(runtime_context.repo_root, runtime_context.runtime_dir, operation_log)
  copy_file(
    runtime_context.repo_root,
    runtime_context.asset_root / "agents.toml",
    runtime_context.runtime_dir / "agents.toml",
    operation_log,
  )
  locked_assets.append(
    LockedAsset(
      "agents.toml",
      relative(runtime_context.repo_root, runtime_context.runtime_dir / "agents.toml"),
      sha256_file(runtime_context.asset_root / "agents.toml"),
    )
  )

  for entry in selected_entries(
    runtime_context.manifest, runtime_context.providers, runtime_context.skills
  ):
    if entry.source in {".rules", "skills"}:
      continue
    source = runtime_context.asset_root / entry.source
    destination = runtime_destination(runtime_context.runtime_dir, entry)
    copy_path(runtime_context.repo_root, source, destination, operation_log)
    locked_assets.extend(lock_entries(runtime_context.repo_root, source, destination, entry.source))

  for skill in runtime_context.skills:
    source = runtime_context.asset_root / "skills" / skill
    destination = runtime_context.runtime_dir / "skills" / skill
    copy_path(runtime_context.repo_root, source, destination, operation_log)
    locked_assets.extend(
      lock_entries(runtime_context.repo_root, source, destination, f"skills/{skill}")
    )

  render_rules(runtime_context, operation_log)
  locked_assets.extend(compiled_assets)

  for entry in selected_entries(
    runtime_context.manifest, runtime_context.providers, runtime_context.skills
  ):
    if not entry.link:
      continue
    source = (
      runtime_context.repo_root / ".rules"
      if entry.source == ".rules"
      else runtime_destination(runtime_context.runtime_dir, entry)
    )
    backup_rel = link_path(
      runtime_context.repo_root,
      source,
      runtime_context.repo_root / entry.destination,
      operation_log,
    )
    locked_links.append(
      LockedLink(
        destination=entry.destination,
        target=os.path.relpath(source, (runtime_context.repo_root / entry.destination).parent),
        provider=entry.provider,
        backup=backup_rel,
      )
    )

  skipped_stale_links = remove_stale_links(
    runtime_context.repo_root, previous_lock, locked_links, operation_log
  )
  locked_links.extend(skipped_stale_links)
  skipped_stale_assets = remove_stale_assets(
    runtime_context.repo_root, previous_lock, locked_assets, operation_log
  )
  locked_assets.extend(skipped_stale_assets)
  validate_locked_asset_destinations_unique(locked_assets)

  if dry_run:
    operation_log.add("would write .agents/dotagents.lock")
  else:
    generated_at = previous_lock.generated_at if locked and previous_lock else None
    write_lock(
      lock_path,
      compute_manifest_sha256(runtime_context),
      runtime_context.providers,
      unique_locked_assets(locked_assets),
      unique_locked_links(locked_links),
      skills=runtime_context.skills,
      skillfile_sha256=compute_skillfile_sha256(runtime_context.repo_root),
      generated_at=generated_at,
    )
    operation_log.add("wrote .agents/dotagents.lock")

  return operation_log


def compiled_lock_entries(repo_root: Path, previous_lock: RuntimeLock | None) -> list[LockedAsset]:
  build_manifest = load_build_manifest_for_sync(repo_root, previous_lock)
  if build_manifest is None:
    return []

  manifest_path = repo_root / BUILD_MANIFEST_DESTINATION
  locked_assets = [
    LockedAsset(
      source=BUILD_MANIFEST_DESTINATION,
      destination=BUILD_MANIFEST_DESTINATION,
      sha256=sha256_file(manifest_path),
    )
  ]
  seen_destinations = {BUILD_MANIFEST_DESTINATION}
  for entry in build_manifest.artifacts:
    destination = validate_compiled_artifact_destination(entry.artifact)
    if destination in seen_destinations:
      raise DotagentsError(f"duplicate compiled artifact: {destination}")
    seen_destinations.add(destination)
    artifact_path = repo_root / destination
    if not artifact_path.is_file():
      raise DotagentsError(f"compiled artifact missing: {destination}")
    actual_sha256 = sha256_file(artifact_path)
    if actual_sha256 != entry.sha256:
      raise DotagentsError(
        f"compiled artifact changed since build manifest: {destination}; "
        "rerun the compiler before sync"
      )
    locked_assets.append(
      LockedAsset(source=f"compiled:{destination}", destination=destination, sha256=entry.sha256)
    )
  return locked_assets


def validate_compiled_assets_do_not_conflict(
  runtime_context: RuntimeContext, compiled_assets: list[LockedAsset]
) -> None:
  skill_prefixes = {skill: f".agents/skills/{skill}/" for skill in runtime_context.skills}
  for asset in compiled_assets:
    for skill, prefix in skill_prefixes.items():
      if asset.destination.startswith(prefix):
        raise DotagentsError(f"compiled artifact conflicts with managed skill: {skill}")


def load_build_manifest_for_sync(
  repo_root: Path, previous_lock: RuntimeLock | None
) -> BuildManifest | None:
  manifest_path = repo_root / BUILD_MANIFEST_DESTINATION
  if not manifest_path.exists():
    if previous_lock is not None and any(
      asset.destination == BUILD_MANIFEST_DESTINATION for asset in previous_lock.assets
    ):
      raise DotagentsError(
        "compiled build manifest missing; restore .agents/build/manifest.json "
        "or run the compiler before sync"
      )
    return None

  try:
    return read_build_manifest(manifest_path)
  except CompilerError as exc:
    raise DotagentsError(str(exc)) from exc


def validate_compiled_artifact_destination(destination: str) -> str:
  try:
    safe_destination = validate_relative_output_path(destination)
  except CompilerError as exc:
    raise DotagentsError(str(exc)) from exc
  if not safe_destination.startswith(".agents/"):
    raise DotagentsError(f"compiled artifact must be under .agents: {safe_destination}")
  return safe_destination


def compiled_staleness_messages(repo_root: Path) -> list[str]:
  manifest_path = repo_root / BUILD_MANIFEST_DESTINATION
  if not manifest_path.exists():
    return []
  try:
    build_manifest = read_build_manifest(manifest_path)
  except CompilerError as exc:
    return [f"compiled artifacts: build manifest error: {exc}"]

  messages: list[str] = []
  for source in build_manifest.sources:
    message = compiled_source_staleness_message(repo_root, source)
    if message:
      messages.append(message)
  return messages


def compiled_group_statuses(repo_root: Path) -> tuple[CompiledGroupStatus, ...]:
  manifest_path = repo_root / BUILD_MANIFEST_DESTINATION
  if not manifest_path.exists():
    return (CompiledGroupStatus("compiled artifacts", "ok", ("no compiled artifacts",)),)
  try:
    build_manifest = read_build_manifest(manifest_path)
  except CompilerError as exc:
    return (
      CompiledGroupStatus(
        "compiled artifacts",
        "invalid",
        (f"compiled artifacts: build manifest error: {exc}",),
      ),
    )

  groups = build_manifest.groups or (
    BuildGroup(
      id="compiled artifacts",
      compiler="unknown",
      output_prefix=".agents",
      artifacts=build_manifest.artifacts,
      sources=build_manifest.sources,
    ),
  )
  return tuple(compiled_group_status(repo_root, group) for group in groups)


def compiled_group_status(repo_root: Path, group: BuildGroup) -> CompiledGroupStatus:
  messages: list[str] = []
  for artifact in group.artifacts:
    message = compiled_artifact_status_message(repo_root, artifact)
    if message:
      messages.append(message)
  for source in group.sources:
    message = compiled_source_staleness_message(repo_root, source)
    if message:
      messages.append(message)
  return CompiledGroupStatus(group.id, compiled_status_from_messages(messages), tuple(messages))


def compiled_artifact_status_message(
  repo_root: Path,
  artifact: BuildManifestEntry,
) -> str | None:
  try:
    destination = validate_compiled_artifact_destination(artifact.artifact)
  except DotagentsError as exc:
    return f"compiled artifacts invalid: {exc}"
  path = repo_root / destination
  if not path.is_file():
    return f"compiled artifact missing: {destination}"
  actual_sha256 = sha256_file(path)
  if actual_sha256 != artifact.sha256:
    return f"compiled artifact changed since build manifest: {destination}"
  return None


def compiled_status_from_messages(
  messages: list[str],
) -> Literal["ok", "stale", "missing", "invalid"]:
  if not messages:
    return "ok"
  if any("invalid" in message or "error" in message for message in messages):
    return "invalid"
  if any("missing" in message for message in messages):
    return "missing"
  return "stale"


def compiled_source_staleness_message(repo_root: Path, source: BuildSource) -> str | None:
  if source.kind == "file":
    try:
      reference = validate_relative_output_path(source.reference)
    except CompilerError as exc:
      return f"compiled artifacts stale: {exc}"
    return compiled_path_staleness(
      repo_root,
      reference,
      source.version,
      missing_label="file source",
      hash_label="file",
      changed_label="file source",
    )
  if source.kind == "package":
    if source.reference == "dotagents" and source.version != package_version():
      return "compiled artifacts stale: dotagents package changed"
    return None
  if source.kind == "variables":
    return None
  if source.kind in {"mcp", "mcp-command", "github-skill"}:
    return None
  if source.kind == "mcp-metadata":
    try:
      _, _, reference = parse_mcp_metadata_reference(source.reference)
      reference = validate_relative_output_path(reference)
    except CompilerError as exc:
      return f"compiled artifacts stale: {exc}"
    return compiled_path_staleness(
      repo_root,
      reference,
      source.version,
      missing_label="MCP metadata source",
      hash_label="MCP metadata source",
      changed_label="MCP metadata source",
    )
  if source.kind == "template":
    return compiled_file_like_source_staleness(repo_root, source, "template source")
  if source.kind == "template-variables":
    return compiled_file_like_source_staleness(repo_root, source, "template variables")
  return f"compiled artifacts stale: unrecognized source kind: {source.kind}"


def compiled_file_like_source_staleness(
  repo_root: Path,
  source: BuildSource,
  label: str,
) -> str | None:
  try:
    _, reference = parse_template_source_reference(source.reference)
    if reference == "<inline>":
      return None
    reference = validate_relative_output_path(reference)
  except CompilerError as exc:
    return f"compiled artifacts stale: {exc}"
  return compiled_path_staleness(
    repo_root,
    reference,
    source.version,
    missing_label=label,
    hash_label=label,
    changed_label=label,
  )


def compiled_path_staleness(
  repo_root: Path,
  reference: str,
  expected_version: str,
  missing_label: str,
  hash_label: str,
  changed_label: str,
) -> str | None:
  path = repo_root / reference
  if not path.is_file():
    return f"compiled artifacts stale: {missing_label} missing: {reference}"
  try:
    current_version = sha256_file(path)
  except OSError as exc:
    return f"compiled artifacts stale: cannot hash {hash_label}: {reference}: {exc}"
  if current_version != expected_version:
    return f"compiled artifacts stale: {changed_label} changed: {reference}"
  return None


def remove_stale_links(
  repo_root: Path,
  previous_lock: RuntimeLock | None,
  locked_links: list[LockedLink],
  operation_log: OperationLog,
) -> list[LockedLink]:
  if previous_lock is None:
    return []

  current_destinations = {link.destination for link in locked_links}
  skipped_links: list[LockedLink] = []
  prune_candidates: set[Path] = set()
  for link in previous_lock.links:
    if link.destination in current_destinations:
      continue
    destination = repo_root / link.destination
    removed = remove_locked_link(repo_root, destination, link.target, operation_log)
    if not removed:
      skipped_links.append(link)
    collect_parents(repo_root, destination, prune_candidates)

  prune_empty_dirs(repo_root, prune_candidates, operation_log)
  return skipped_links


def remove_stale_assets(
  repo_root: Path,
  previous_lock: RuntimeLock | None,
  locked_assets: list[LockedAsset],
  operation_log: OperationLog,
) -> list[LockedAsset]:
  if previous_lock is None:
    return []

  current_destinations = {asset.destination for asset in locked_assets}
  skipped_assets: list[LockedAsset] = []
  prune_candidates: set[Path] = set()
  for asset in previous_lock.assets:
    if asset.destination in current_destinations:
      continue
    destination = repo_root / asset.destination
    if not remove_locked_asset(repo_root, destination, asset.sha256, operation_log):
      skipped_assets.append(asset)
    collect_parents(repo_root, destination, prune_candidates)
  prune_empty_dirs(repo_root, prune_candidates, operation_log)
  return skipped_assets


def runtime_destination(runtime_dir: Path, entry: SyncEntry) -> Path:
  if entry.source == "skills":
    return runtime_dir / "skills"
  source = Path(entry.source)
  first = source.parts[0]
  if first in {"scripts", "skills"}:
    return runtime_dir / source
  if entry.provider and first == entry.provider:
    suffix = Path(*source.parts[1:]) if len(source.parts) > 1 else Path()
    return runtime_dir / "providers" / entry.provider / suffix
  raise DotagentsError(f"unsupported manifest source root: {entry.source}")


def render_rules(runtime_context: RuntimeContext, operation_log: OperationLog) -> None:
  shared_rules = runtime_context.asset_root / "rules" / "rules.md"
  try:
    shared = shared_rules.read_text(encoding="utf-8").rstrip()
  except OSError as exc:
    raise DotagentsError(f"cannot read bundled rules file: {shared_rules}") from exc
  chunks = ["<!-- Shared agent rules from dotagents package rules/rules.md -->", "", shared]
  local = runtime_context.repo_root / ".rules.local"
  if local.exists():
    chunks.extend(
      [
        "",
        "",
        "<!-- Local repo rules from .rules.local -->",
        "",
        local.read_text(encoding="utf-8").rstrip(),
      ]
    )
  write_text(
    runtime_context.repo_root,
    runtime_context.repo_root / ".rules",
    "\n".join(chunks) + "\n",
    operation_log,
  )


def lock_entries(
  repo_root: Path, source: Path, destination: Path, source_name: str
) -> list[LockedAsset]:
  if source.is_file():
    return [LockedAsset(source_name, relative(repo_root, destination), sha256_file(source))]

  entries: list[LockedAsset] = []
  for path in sorted(source.rglob("*")):
    if path.is_file():
      relative_path = path.relative_to(source)
      entries.append(
        LockedAsset(
          str(Path(source_name) / relative_path),
          relative(repo_root, destination / relative_path),
          sha256_file(path),
        )
      )
  return entries


def unique_locked_assets(locked_assets: list[LockedAsset]) -> list[LockedAsset]:
  unique: dict[tuple[str, str], LockedAsset] = {}
  for asset in locked_assets:
    unique[(asset.source, asset.destination)] = asset
  return list(unique.values())


def validate_locked_asset_destinations_unique(locked_assets: list[LockedAsset]) -> None:
  assets_by_destination: dict[str, LockedAsset] = {}
  for asset in locked_assets:
    existing = assets_by_destination.get(asset.destination)
    if existing is not None and existing.source != asset.source:
      raise DotagentsError(
        "managed asset destination collision: "
        f"{asset.destination} from {existing.source} and {asset.source}"
      )
    assets_by_destination[asset.destination] = asset


def unique_locked_links(locked_links: list[LockedLink]) -> list[LockedLink]:
  unique: dict[str, LockedLink] = {}
  for link in locked_links:
    unique[link.destination] = link
  return list(unique.values())


def copy_path(
  repo_root: Path, source: Path, destination: Path, operation_log: OperationLog
) -> None:
  if source.is_dir():
    for path in sorted(source.rglob("*")):
      if path.is_file():
        copy_file(repo_root, path, destination / path.relative_to(source), operation_log)
    return
  copy_file(repo_root, source, destination, operation_log)


def copy_file(
  repo_root: Path, source: Path, destination: Path, operation_log: OperationLog
) -> None:
  if (
    destination.exists()
    and destination.is_file()
    and filecmp.cmp(source, destination, shallow=False)
  ):
    operation_log.add(f"ok {relative(repo_root, destination)}")
    return
  if destination.exists() and destination.is_symlink():
    raise DotagentsError(
      f"refusing to replace symlink with managed file: {relative(repo_root, destination)}"
    )
  if operation_log.dry_run:
    operation_log.add(f"would copy {relative(repo_root, destination)}")
    return
  destination.parent.mkdir(parents=True, exist_ok=True)
  shutil.copy2(source, destination)
  operation_log.add(f"copied {relative(repo_root, destination)}")


def write_text(
  repo_root: Path, destination: Path, content: str, operation_log: OperationLog
) -> None:
  if (
    destination.exists()
    and destination.is_file()
    and destination.read_text(encoding="utf-8") == content
  ):
    operation_log.add(f"ok {relative(repo_root, destination)}")
    return
  if destination.exists() and destination.is_symlink():
    raise DotagentsError(
      f"refusing to replace symlink with managed file: {relative(repo_root, destination)}"
    )
  if operation_log.dry_run:
    operation_log.add(f"would write {relative(repo_root, destination)}")
    return
  destination.write_text(content, encoding="utf-8")
  operation_log.add(f"wrote {relative(repo_root, destination)}")


def link_path(
  repo_root: Path, source: Path, destination: Path, operation_log: OperationLog
) -> str | None:
  """Return the relative path to the backup file if one was created or already exists, else None.

  Raises:
    DotagentsError: if a `.bak` file already exists at the backup path (conflict must be resolved manually).
  """
  backup = destination.parent / (destination.name + ".bak")

  if destination.exists() and not destination.is_symlink():
    if backup.exists():
      raise DotagentsError(
        f"backup already exists: {relative(repo_root, backup)}; resolve manually and re-run"
      )
    if operation_log.dry_run:
      operation_log.add(
        f"would back up {relative(repo_root, destination)} -> {relative(repo_root, backup)}"
      )
    else:
      destination.rename(backup)
      operation_log.add(
        f"backed up {relative(repo_root, destination)} -> {relative(repo_root, backup)}"
      )
    backup_rel: str | None = relative(repo_root, backup)
  else:
    backup_rel = relative(repo_root, backup) if backup.exists() else None

  target = os.path.relpath(source, destination.parent)
  if destination.is_symlink() and os.readlink(destination) == target:
    operation_log.add(f"ok {relative(repo_root, destination)}")
    return backup_rel

  if operation_log.dry_run:
    operation_log.add(f"would link {relative(repo_root, destination)} -> {target}")
    return backup_rel

  destination.parent.mkdir(parents=True, exist_ok=True)
  if destination.exists() or destination.is_symlink():
    destination.unlink()
  destination.symlink_to(target)
  operation_log.add(f"linked {relative(repo_root, destination)} -> {target}")
  return backup_rel


def ensure_dir(repo_root: Path, path: Path, operation_log: OperationLog) -> None:
  if path.exists():
    if not path.is_dir():
      raise DotagentsError(f"expected directory: {relative(repo_root, path)}")
    return
  if operation_log.dry_run:
    operation_log.add(f"would create {relative(repo_root, path)}")
    return
  path.mkdir(parents=True)
  operation_log.add(f"created {relative(repo_root, path)}")


def remove_locked_link(
  repo_root: Path, destination: Path, expected_target: str, operation_log: OperationLog
) -> bool:
  display = relative(repo_root, destination)
  if not destination.exists() and not destination.is_symlink():
    operation_log.add(f"missing {display}")
    return True
  if not destination.is_symlink():
    operation_log.add(f"skip user-owned {display}; remove manually after verifying")
    return False

  actual_target = os.readlink(destination)
  if actual_target != expected_target:
    operation_log.add(f"skip unexpected symlink {display}; remove manually after verifying")
    return False

  if operation_log.dry_run:
    operation_log.add(f"would remove {display}")
    operation_log.pending_removals.add(destination)
    return True
  destination.unlink()
  operation_log.add(f"removed {display}")
  return True


def restore_backup(
  repo_root: Path, backup_path: Path, destination: Path, operation_log: OperationLog
) -> None:
  if not backup_path.exists():
    operation_log.add(f"backup missing {relative(repo_root, backup_path)}; skipped restore")
    return
  if operation_log.dry_run:
    operation_log.add(
      f"would restore {relative(repo_root, backup_path)} -> {relative(repo_root, destination)}"
    )
    return
  backup_path.rename(destination)
  operation_log.add(
    f"restored {relative(repo_root, backup_path)} -> {relative(repo_root, destination)}"
  )


def remove_locked_asset(
  repo_root: Path, path: Path, expected_sha256: str, operation_log: OperationLog
) -> bool:
  """Return True if the asset was removed (or would be in dry-run), False if skipped."""
  display = relative(repo_root, path)
  if not path.exists() and not path.is_symlink():
    operation_log.add(f"missing {display}")
    return True
  if path.is_symlink() or not path.is_file():
    operation_log.add(f"skip unexpected {display}; remove manually after verifying")
    return False
  if sha256_file(path) != expected_sha256:
    operation_log.add(f"skip changed {display}; remove manually after verifying")
    return False

  if operation_log.dry_run:
    operation_log.add(f"would remove {display}")
    operation_log.pending_removals.add(path)
    return True
  path.unlink()
  operation_log.add(f"removed {display}")
  return True


def remove_generated_rules(repo_root: Path, operation_log: OperationLog) -> None:
  rules = repo_root / ".rules"
  display = relative(repo_root, rules)
  if not rules.exists() and not rules.is_symlink():
    operation_log.add(f"missing {display}")
    return
  if rules.is_symlink() or not rules.is_file():
    operation_log.add(f"skip unexpected {display}; remove manually after verifying")
    return
  try:
    content = rules.read_text(encoding="utf-8")
  except OSError:
    operation_log.add(f"skip unreadable {display}; remove manually after verifying")
    return
  if "<!-- Shared agent rules from dotagents package rules/rules.md -->" not in content:
    operation_log.add(f"skip user-owned {display}; remove manually after verifying")
    return

  if operation_log.dry_run:
    operation_log.add(f"would remove {display}")
    operation_log.pending_removals.add(rules)
    return
  rules.unlink()
  operation_log.add(f"removed {display}")


def remove_lockfile(repo_root: Path, lock_path: Path, operation_log: OperationLog) -> None:
  display = relative(repo_root, lock_path)
  if not lock_path.exists():
    operation_log.add(f"missing {display}")
    return
  if not lock_path.is_file():
    operation_log.add(f"skip unexpected {display}; remove manually after verifying")
    return

  if operation_log.dry_run:
    operation_log.add(f"would remove {display}")
    operation_log.pending_removals.add(lock_path)
    return
  lock_path.unlink()
  operation_log.add(f"removed {display}")


def collect_parents(repo_root: Path, path: Path, candidates: set[Path]) -> None:
  current = path.parent
  while current != repo_root and repo_root in current.parents:
    candidates.add(current)
    current = current.parent


def prune_empty_dirs(repo_root: Path, candidates: set[Path], operation_log: OperationLog) -> None:
  for path in sorted(candidates, key=lambda item: len(item.parts), reverse=True):
    if path == repo_root or not path.exists() or not path.is_dir():
      continue
    display = relative(repo_root, path)
    if operation_log.dry_run:
      remaining = [child for child in path.iterdir() if child not in operation_log.pending_removals]
      if not remaining:
        operation_log.add(f"would remove empty {display}")
        operation_log.pending_removals.add(path)
    else:
      try:
        next(path.iterdir())
      except StopIteration:
        path.rmdir()
        operation_log.add(f"removed empty {display}")


def relative(base: Path, path: Path) -> str:
  try:
    return os.path.relpath(path, base)
  except ValueError:
    return str(path)
