"""Managed runtime materialization."""

import filecmp
import os
import shutil
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from dotagents.assets import asset_root
from dotagents.compiler import (
  BuildGroup,
  BuildManifest,
  BuildManifestEntry,
  BuildSource,
  CompilerError,
  parse_mcp_metadata_reference,
  parse_template_source_reference,
  read_build_manifest,
  validate_relative_output_path,
)
from dotagents.errors import DotagentsError
from dotagents.lockfile import (
  LockedAsset,
  LockedLink,
  RuntimeLock,
  backup_fingerprint,
  read_lock,
  sha256_file,
  write_lock,
)
from dotagents.manifest import (
  Manifest,
  SyncEntry,
  load_manifest,
  scope_applies,
  selected_entries,
  selected_providers,
)
from dotagents.skillfile import REQUIRED_SKILLS, available_skills, resolve_skillfile, skillfile_path
from dotagents.version import package_version

OPT_IN_SKILLS = frozenset({"prek-bootstrap", "review-saga", "saga"})
BUILD_MANIFEST_DESTINATION = ".agents/build/manifest.json"
CAPABILITY_INDEX_SCHEMA_VERSION = 1
WOULD_BACK_UP_PREFIX = "would back up "
CapabilityStatus = Literal["ok", "stale", "missing", "invalid"]


@dataclass
class OperationLog:
  dry_run: bool = False
  lines: list[str] = field(default_factory=list)
  pending_removals: set[Path] = field(default_factory=set)
  planned_backups: list[tuple[Path, Path]] = field(default_factory=list)
  created_backups: list[tuple[Path, Path]] = field(default_factory=list)

  def add(self, message: str) -> None:
    self.lines.append(message)


@dataclass(frozen=True)
class BackupRecord:
  """A backup's location and a fingerprint of what it held at creation time.

  `fingerprint` is typed as optional because `read_lock` only enforces its presence at the
  lockfile boundary (a lock with `backup` but no `backup_fingerprint` fails to parse at all,
  forcing `dotagents update` — see `SUPPORTED_LOCKFILE_VERSION`), not at this dataclass's
  construction sites.
  """

  path: str
  fingerprint: str | None


@dataclass(frozen=True)
class RuntimeContext:
  repo_root: Path
  runtime_dir: Path
  asset_root: Path
  manifest: Manifest
  providers: tuple[str, ...]
  skills: tuple[str, ...]
  is_global: bool


@dataclass(frozen=True)
class RuntimeDrift:
  kind: Literal["version", "manifest"]
  runtime_value: str
  package_value: str

  def update_guidance(self) -> str:
    if self.kind == "version":
      return (
        f"runtime was generated by dotagents {self.runtime_value} but installed "
        f"package is {self.package_value}. Run: uv run dotagents update"
      )
    return "agents.toml manifest changed. Run: uv run dotagents update"


@dataclass(frozen=True)
class CompiledGroupStatus:
  id: str
  status: CapabilityStatus
  messages: tuple[str, ...] = ()


@dataclass(frozen=True)
class CapabilitySkill:
  name: str
  kind: Literal["packaged", "compiled"]
  path: str
  status: CapabilityStatus
  group_id: str | None = None
  compiler: str | None = None
  messages: tuple[str, ...] = ()


@dataclass(frozen=True)
class CapabilityGroup:
  id: str
  compiler: str
  output_prefix: str
  status: CapabilityStatus
  messages: tuple[str, ...] = ()


@dataclass(frozen=True)
class CapabilityIndex:
  schema_version: int
  skills: tuple[CapabilitySkill, ...]
  compiled_groups: tuple[CapabilityGroup, ...]


def check_drift(
  kind: Literal["version", "manifest"], runtime_value: str, package_value: str
) -> RuntimeDrift | None:
  if runtime_value == package_value:
    return None
  return RuntimeDrift(kind=kind, runtime_value=runtime_value, package_value=package_value)


def version_drift(runtime_lock: RuntimeLock) -> RuntimeDrift | None:
  return check_drift("version", runtime_lock.version, package_version())


def compute_manifest_sha256(runtime_context: RuntimeContext) -> str:
  return sha256_file(runtime_context.asset_root / "agents.toml")


def compute_skillfile_sha256(repo_root: Path) -> str | None:
  path = skillfile_path(repo_root)
  return sha256_file(path) if path.exists() else None


def manifest_drift(
  runtime_context: RuntimeContext, runtime_lock: RuntimeLock
) -> RuntimeDrift | None:
  return check_drift(
    "manifest", runtime_lock.manifest_sha256, compute_manifest_sha256(runtime_context)
  )


def default_skills(asset_root: Path) -> tuple[str, ...]:
  return tuple(skill for skill in available_skills(asset_root) if skill not in OPT_IN_SKILLS)


def effective_skills(asset_root: Path, selected: tuple[str, ...]) -> tuple[str, ...]:
  """Validate required-skill packaging integrity, then pass `selected` through unchanged.

  `dotagents-discovery` is not force-added here: `default_skills` already
  includes it (it is not in `OPT_IN_SKILLS`), and `render_template` lists it
  pre-selected in freshly generated Skillfiles. A Skillfile that omits it is
  an explicit, auditable choice — the same as omitting any other skill —
  not something this function should silently override.

  Raises:
    DotagentsError: a skill in `REQUIRED_SKILLS` has no matching asset
      directory, indicating a broken or incomplete package.
  """
  available = set(available_skills(asset_root))
  missing_required = [skill for skill in REQUIRED_SKILLS if skill not in available]
  if missing_required:
    raise DotagentsError(
      f"required skill(s) missing from packaged assets: {', '.join(missing_required)}"
    )
  return selected


def is_global_root(root: Path) -> bool:
  return root.resolve() == Path.home().resolve()


def build_context(repo_root: Path, requested_providers: tuple[str, ...] = ()) -> RuntimeContext:
  root = repo_root.resolve()
  assets = asset_root()
  manifest = load_manifest(assets)
  configured = requested_providers or configured_providers(root, manifest)
  providers = selected_providers(manifest, configured)
  selected_skills = (
    resolve_skillfile(root, assets) if (root / "Skillfile").exists() else default_skills(assets)
  )
  skills = effective_skills(assets, selected_skills)
  return RuntimeContext(
    repo_root=root,
    runtime_dir=root / ".agents",
    asset_root=assets,
    manifest=manifest,
    providers=providers,
    skills=skills,
    is_global=is_global_root(root),
  )


def configured_providers(repo_root: Path, manifest: Manifest) -> tuple[str, ...]:
  lock_path = repo_root / ".agents" / "dotagents.lock"
  if not lock_path.exists():
    return manifest.providers
  return read_lock(lock_path).providers


def init_runtime(
  repo_root: Path, providers: tuple[str, ...], dry_run: bool = False, locked: bool = False
) -> OperationLog:
  runtime_context = build_context(repo_root, providers)
  if locked:
    validate_locked_runtime(runtime_context)
  return sync_runtime(runtime_context, dry_run=dry_run, locked=locked)


def sync_existing(repo_root: Path, dry_run: bool = False, locked: bool = False) -> OperationLog:
  runtime_context = build_context(repo_root)
  lock_path = runtime_context.runtime_dir / "dotagents.lock"
  if lock_path.exists():
    runtime_lock = read_lock(lock_path)
    drift = version_drift(runtime_lock)
    if drift:
      raise DotagentsError(drift.update_guidance())
    manifest = manifest_drift(runtime_context, runtime_lock)
    if manifest:
      raise DotagentsError(manifest.update_guidance())
  elif locked:
    raise DotagentsError("cannot sync --locked: missing .agents/dotagents.lock")
  if locked:
    validate_locked_runtime(runtime_context)
  operation_log = sync_runtime(runtime_context, dry_run=dry_run, locked=locked)
  operation_log.lines.append("sync used current dotagents package assets")
  return operation_log


def validate_locked_runtime(runtime_context: RuntimeContext) -> RuntimeLock:
  lock_path = runtime_context.runtime_dir / "dotagents.lock"
  if not lock_path.exists():
    raise DotagentsError("cannot use --locked: missing .agents/dotagents.lock")
  if not skillfile_path(runtime_context.repo_root).exists():
    raise DotagentsError("cannot use --locked: missing Skillfile")
  runtime_lock = read_lock(lock_path)
  drift = version_drift(runtime_lock)
  if drift:
    raise DotagentsError(drift.update_guidance())
  manifest = manifest_drift(runtime_context, runtime_lock)
  if manifest:
    raise DotagentsError(manifest.update_guidance())
  if runtime_lock.skills != runtime_context.skills:
    raise DotagentsError("Skillfile selection differs from lockfile; run: uv run dotagents sync")
  current_skillfile_sha256 = compute_skillfile_sha256(runtime_context.repo_root)
  if runtime_lock.skillfile_sha256 != current_skillfile_sha256:
    raise DotagentsError("Skillfile changed since lockfile; run: uv run dotagents sync")
  return runtime_lock


def update_existing(repo_root: Path, dry_run: bool = False) -> OperationLog:
  runtime_context = build_context(repo_root)
  lock_path = runtime_context.runtime_dir / "dotagents.lock"
  previous_version = read_lock(lock_path).version if lock_path.exists() else None
  operation_log = sync_runtime(runtime_context, dry_run=dry_run)
  installed_version = package_version()
  if previous_version is None:
    operation_log.lines.append(f"update created runtime with dotagents {installed_version}")
  elif previous_version == installed_version:
    operation_log.lines.append(f"runtime at {installed_version}; refreshed managed files")
  else:
    operation_log.lines.append(f"updated runtime: {previous_version} -> {installed_version}")
  return operation_log


def uninstall_existing(repo_root: Path, dry_run: bool = False) -> OperationLog:
  root = repo_root.resolve()
  runtime_dir = root / ".agents"
  lock_path = runtime_dir / "dotagents.lock"
  if not lock_path.exists():
    raise DotagentsError("cannot uninstall: missing .agents/dotagents.lock")

  runtime_lock = read_lock(lock_path)
  operation_log = OperationLog(dry_run=dry_run)
  prune_candidates: set[Path] = set()

  for link in runtime_lock.links:
    destination = root / link.destination
    remove_link_with_backup(root, link, destination, operation_log)
    collect_parents(root, destination, prune_candidates)

  remove_generated_rules(
    root, operation_log, runtime_lock.rules_backup, runtime_lock.rules_backup_fingerprint
  )
  collect_parents(root, root / ".rules", prune_candidates)

  for asset in sorted(runtime_lock.assets, key=lambda item: item.destination, reverse=True):
    path = root / asset.destination
    remove_locked_asset(root, path, asset.sha256, operation_log)
    collect_parents(root, path, prune_candidates)

  remove_lockfile(root, lock_path, operation_log)
  collect_parents(root, lock_path, prune_candidates)
  prune_empty_dirs(root, prune_candidates, operation_log)
  operation_log.add(
    "would uninstall dotagents runtime"
    if operation_log.dry_run
    else "uninstalled dotagents runtime"
  )
  return operation_log


def read_provider_operation_state(
  repo_root: Path, lock_path: Path
) -> tuple[RuntimeLock, RuntimeContext]:
  current_lock = read_lock(lock_path)
  drift = version_drift(current_lock)
  if drift:
    raise DotagentsError(drift.update_guidance())
  runtime_context = build_context(repo_root, current_lock.providers)
  manifest = manifest_drift(runtime_context, current_lock)
  if manifest:
    raise DotagentsError(manifest.update_guidance())
  return current_lock, runtime_context


def add_provider(repo_root: Path, provider: str, dry_run: bool = False) -> OperationLog:
  root = repo_root.resolve()
  lock_path = root / ".agents" / "dotagents.lock"
  if not lock_path.exists():
    raise DotagentsError(
      "cannot add provider: missing .agents/dotagents.lock. Run: uv run dotagents init"
    )
  current_lock, _ = read_provider_operation_state(root, lock_path)
  if provider in current_lock.providers:
    operation_log = OperationLog(dry_run=dry_run)
    operation_log.add(f"provider already configured: {provider}")
    return operation_log
  new_providers = (*current_lock.providers, provider)
  return sync_runtime(build_context(root, new_providers), dry_run=dry_run)


def remove_provider(repo_root: Path, provider: str, dry_run: bool = False) -> OperationLog:
  root = repo_root.resolve()
  runtime_dir = root / ".agents"
  lock_path = runtime_dir / "dotagents.lock"
  if not lock_path.exists():
    raise DotagentsError("cannot remove provider: missing .agents/dotagents.lock")

  current_lock, runtime_context = read_provider_operation_state(root, lock_path)
  if provider not in current_lock.providers:
    raise DotagentsError(f"provider not configured: {provider}")

  remaining_providers = tuple(p for p in current_lock.providers if p != provider)
  operation_log = OperationLog(dry_run=dry_run)
  prune_candidates: set[Path] = set()

  skipped_links: list[LockedLink] = []
  for link in (link for link in current_lock.links if link.provider == provider):
    destination = root / link.destination
    if not remove_link_with_backup(root, link, destination, operation_log):
      skipped_links.append(link)
    collect_parents(root, destination, prune_candidates)

  provider_prefix = f".agents/providers/{provider}/"
  skipped_assets: list[LockedAsset] = []
  for asset in sorted(
    (a for a in current_lock.assets if a.destination.startswith(provider_prefix)),
    key=lambda a: a.destination,
    reverse=True,
  ):
    path = root / asset.destination
    removed = remove_locked_asset(root, path, asset.sha256, operation_log)
    if not removed:
      skipped_assets.append(asset)
    collect_parents(root, path, prune_candidates)

  prune_empty_dirs(root, prune_candidates, operation_log)

  if not dry_run:
    remaining_assets = [
      a for a in current_lock.assets if not a.destination.startswith(provider_prefix)
    ] + skipped_assets
    remaining_links = [
      migrate_legacy_link_backup(root, link)
      for link in (
        [link for link in current_lock.links if link.provider != provider] + skipped_links
      )
    ]
    rules_backup_record = migrate_legacy_backup(
      root,
      BackupRecord(current_lock.rules_backup, current_lock.rules_backup_fingerprint)
      if current_lock.rules_backup
      else None,
      root / current_lock.rules_backup if current_lock.rules_backup else root,
    )
    write_lock(
      lock_path,
      compute_manifest_sha256(runtime_context),
      remaining_providers,
      remaining_assets,
      remaining_links,
      skills=current_lock.skills,
      skillfile_sha256=current_lock.skillfile_sha256,
      rules_backup=rules_backup_record.path if rules_backup_record else None,
      rules_backup_fingerprint=rules_backup_record.fingerprint if rules_backup_record else None,
    )
    operation_log.add(f"removed provider: {provider}")
  else:
    operation_log.add(f"would remove provider: {provider}")

  return operation_log


def rollback_created_backups(repo_root: Path, operation_log: OperationLog) -> None:
  """Undo backups created earlier in a failed `sync_runtime` call.

  This is deliberately narrow: it undoes backup renames only, not every mutation
  `sync_runtime` may have performed before failing (asset copies, newly-created symlinks,
  stale-entry removals, directory pruning). Those are safe to leave as-is because they're
  each idempotent on retry — a copy re-copies identical content, an already-correct symlink
  is a no-op via `already_linked`, a stale entry already removed is reported as missing and
  treated as done (`remove_locked_link`). `sync_runtime` is not transactional as a whole;
  this function closes the one gap that isn't self-healing on retry.

  Backups are that gap: `sync_runtime` mutates disk incrementally per entry but writes the
  lockfile once, at the end, after every entry succeeds. Without this, a later entry failing
  (e.g. a `.bak` naming collision unrelated to an earlier entry) would leave an earlier
  entry's backup created on disk but never recorded in the lockfile — stranded as untracked
  on retry, since the "don't adopt an unrecorded `.bak`" protection can't tell it apart from
  a genuinely stray file.

  Each restore moves the current `destination` aside (instead of unlinking it) before
  renaming the backup into place, so a `backup.rename()` failure after the move — a
  cross-device rename, a permission change, disk full — doesn't leave `destination` empty.
  On failure the aside file is renamed back so `destination` ends up unchanged rather than
  gone. Every backup is still attempted even if an earlier one fails.

  Raises:
    DotagentsError: if any backup could not be restored, after every backup was attempted.
  """
  failures: list[str] = []
  for destination, backup in reversed(operation_log.created_backups):
    if not backup.exists(follow_symlinks=False):
      continue
    aside: Path | None = None
    moved_aside = False
    try:
      if destination.exists(follow_symlinks=False):
        aside = destination.parent / f"{destination.name}.rollback-{uuid.uuid4().hex}"
        destination.rename(aside)
        moved_aside = True
      backup.rename(destination)
    except OSError as exc:
      detail = f"rollback failed {relative(repo_root, backup)}: {exc}"
      if moved_aside and aside is not None and not destination.exists(follow_symlinks=False):
        try:
          aside.rename(destination)
        except OSError as restore_exc:
          detail += (
            f"; could not restore prior state either ({restore_exc}); "
            f"original content preserved at {relative(repo_root, aside)}"
          )
      operation_log.add(detail)
      failures.append(detail)
      continue
    if moved_aside and aside is not None:
      try:
        if aside.is_symlink() or not aside.is_dir():
          aside.unlink()
        else:
          shutil.rmtree(aside)
      except OSError as cleanup_exc:
        # The restore itself succeeded — `destination` holds the correct content — but the
        # discarded pre-rollback content is now stranded at `aside` instead of removed. Still
        # counts as incomplete: left alone, that stray file is silent disk debris nobody was
        # told about.
        detail = (
          f"restored {relative(repo_root, backup)} -> {relative(repo_root, destination)}, "
          f"but could not remove leftover {relative(repo_root, aside)}: {cleanup_exc}"
        )
        operation_log.add(detail)
        failures.append(detail)
  if failures:
    raise DotagentsError("rollback did not fully complete:\n" + "\n".join(failures))


def sync_runtime(
  runtime_context: RuntimeContext, dry_run: bool = False, locked: bool = False
) -> OperationLog:
  operation_log = OperationLog(dry_run=dry_run)
  try:
    _sync_runtime_body(runtime_context, dry_run, locked, operation_log)
  except Exception as exc:
    if not dry_run:
      try:
        rollback_created_backups(runtime_context.repo_root, operation_log)
      except DotagentsError as rollback_exc:
        # `main()` only special-cases `DotagentsError` for its clean "ERROR: ..." rendering;
        # every other exception type gets a raw traceback instead. Folding the rollback
        # failure into a `DotagentsError` message (regardless of the original exception's
        # type) is what makes it reach that same visible path every time, rather than only
        # when `_sync_runtime_body` happened to raise a `DotagentsError` itself.
        raise DotagentsError(f"{exc}\n{rollback_exc}") from exc
    raise
  return operation_log


def _sync_runtime_body(
  runtime_context: RuntimeContext, dry_run: bool, locked: bool, operation_log: OperationLog
) -> None:
  locked_assets: list[LockedAsset] = []
  locked_links: list[LockedLink] = []
  lock_path = runtime_context.runtime_dir / "dotagents.lock"
  previous_lock = read_lock(lock_path) if lock_path.exists() else None
  compiled_assets = compiled_lock_entries(runtime_context.repo_root, previous_lock)
  validate_compiled_assets_do_not_conflict(runtime_context, compiled_assets)

  ensure_dir(runtime_context.repo_root, runtime_context.runtime_dir, operation_log)
  copy_file(
    runtime_context.repo_root,
    runtime_context.asset_root / "agents.toml",
    runtime_context.runtime_dir / "agents.toml",
    operation_log,
  )
  manifest_sha256 = sha256_file(runtime_context.asset_root / "agents.toml")
  locked_assets.append(
    LockedAsset(
      "agents.toml",
      relative(runtime_context.repo_root, runtime_context.runtime_dir / "agents.toml"),
      manifest_sha256,
    )
  )

  entries = selected_entries(
    runtime_context.manifest, runtime_context.providers, runtime_context.skills
  )
  forced_copy_dirs: set[Path] = set()
  for entry in entries:
    if entry.source in {".rules", "skills"}:
      continue
    applies = scope_applies(entry.scope, runtime_context.is_global)
    if not applies and not entry.always_copy:
      continue
    source = runtime_context.asset_root / entry.source
    destination = runtime_destination(runtime_context.runtime_dir, entry)
    if not applies:
      forced_copy_dirs.add(destination.parent)
    copy_path(runtime_context.repo_root, source, destination, operation_log)
    locked_assets.extend(lock_entries(runtime_context.repo_root, source, destination, entry.source))

  for skill in runtime_context.skills:
    source = runtime_context.asset_root / "skills" / skill
    destination = runtime_context.runtime_dir / "skills" / skill
    copy_path(runtime_context.repo_root, source, destination, operation_log)
    locked_assets.extend(
      lock_entries(runtime_context.repo_root, source, destination, f"skills/{skill}")
    )

  rules_known_backup = (
    BackupRecord(previous_lock.rules_backup, previous_lock.rules_backup_fingerprint)
    if previous_lock and previous_lock.rules_backup
    else None
  )
  rules_backup = render_rules(runtime_context, operation_log, known_backup=rules_known_backup)
  locked_assets.extend(compiled_assets)
  log_compiled_assets(compiled_assets, operation_log)
  validate_locked_asset_destinations_unique(locked_assets)

  previous_link_backups = (
    {
      link.destination: BackupRecord(link.backup, link.backup_fingerprint)
      for link in previous_lock.links
      if link.backup
    }
    if previous_lock
    else {}
  )
  for entry in entries:
    if not entry.link:
      continue
    if not scope_applies(entry.scope, runtime_context.is_global):
      continue
    source = (
      runtime_context.repo_root / ".rules"
      if entry.source == ".rules"
      else runtime_destination(runtime_context.runtime_dir, entry)
    )
    backup_record = link_path(
      runtime_context.repo_root,
      source,
      runtime_context.repo_root / entry.destination,
      operation_log,
      known_backup=previous_link_backups.get(entry.destination),
    )
    locked_links.append(
      LockedLink(
        destination=entry.destination,
        target=os.path.relpath(source, (runtime_context.repo_root / entry.destination).parent),
        provider=entry.provider,
        backup=backup_record.path if backup_record else None,
        backup_fingerprint=backup_record.fingerprint if backup_record else None,
      )
    )

  skipped_stale_links = remove_stale_links(
    runtime_context.repo_root, previous_lock, locked_links, operation_log
  )
  locked_links.extend(skipped_stale_links)
  skipped_stale_assets = remove_stale_assets(
    runtime_context.repo_root, previous_lock, locked_assets, operation_log
  )
  locked_assets.extend(skipped_stale_assets)
  validate_locked_asset_destinations_unique(locked_assets)

  for forced_copy_dir in sorted(forced_copy_dirs):
    operation_log.add(f"add to PATH: {forced_copy_dir}")

  if dry_run:
    operation_log.add("would write .agents/dotagents.lock")
  else:
    generated_at = previous_lock.generated_at if locked and previous_lock else None
    write_lock(
      lock_path,
      manifest_sha256,
      runtime_context.providers,
      unique_locked_assets(locked_assets),
      unique_locked_links(locked_links),
      skills=runtime_context.skills,
      skillfile_sha256=compute_skillfile_sha256(runtime_context.repo_root),
      generated_at=generated_at,
      rules_backup=rules_backup.path if rules_backup else None,
      rules_backup_fingerprint=rules_backup.fingerprint if rules_backup else None,
    )
    operation_log.add("wrote .agents/dotagents.lock")


def compiled_lock_entries(repo_root: Path, previous_lock: RuntimeLock | None) -> list[LockedAsset]:
  build_manifest = load_build_manifest_for_sync(repo_root, previous_lock)
  if build_manifest is None:
    return []

  manifest_path = repo_root / BUILD_MANIFEST_DESTINATION
  locked_assets = [
    LockedAsset(
      source=BUILD_MANIFEST_DESTINATION,
      destination=BUILD_MANIFEST_DESTINATION,
      sha256=sha256_file(manifest_path),
    )
  ]
  seen_destinations = {BUILD_MANIFEST_DESTINATION}
  for entry in build_manifest.artifacts:
    destination = validate_compiled_artifact_destination(entry.artifact)
    if destination in seen_destinations:
      raise DotagentsError(f"duplicate compiled artifact: {destination}")
    seen_destinations.add(destination)
    artifact_path = repo_root / destination
    if not artifact_path.is_file():
      raise DotagentsError(f"compiled artifact missing: {destination}")
    actual_sha256 = sha256_file(artifact_path)
    if actual_sha256 != entry.sha256:
      raise DotagentsError(
        f"compiled artifact changed since build manifest: {destination}; "
        "rerun the compiler before sync"
      )
    locked_assets.append(
      LockedAsset(source=f"compiled:{destination}", destination=destination, sha256=entry.sha256)
    )
  return locked_assets


def log_compiled_assets(compiled_assets: list[LockedAsset], operation_log: OperationLog) -> None:
  verb = "would lock" if operation_log.dry_run else "ok"
  for asset in compiled_assets:
    operation_log.add(f"{verb} {asset.destination}")


def validate_compiled_assets_do_not_conflict(
  runtime_context: RuntimeContext, compiled_assets: list[LockedAsset]
) -> None:
  skill_prefixes = {skill: f".agents/skills/{skill}/" for skill in runtime_context.skills}
  for asset in compiled_assets:
    for skill, prefix in skill_prefixes.items():
      if asset.destination.startswith(prefix):
        raise DotagentsError(f"compiled artifact conflicts with managed skill: {skill}")


def load_build_manifest_for_sync(
  repo_root: Path, previous_lock: RuntimeLock | None
) -> BuildManifest | None:
  manifest_path = repo_root / BUILD_MANIFEST_DESTINATION
  if not manifest_path.exists():
    if previous_lock is not None and any(
      asset.destination == BUILD_MANIFEST_DESTINATION for asset in previous_lock.assets
    ):
      raise DotagentsError(
        "compiled build manifest missing; restore .agents/build/manifest.json "
        "or run the compiler before sync"
      )
    return None

  try:
    return read_build_manifest(manifest_path)
  except CompilerError as exc:
    raise DotagentsError(str(exc)) from exc


def validate_compiled_artifact_destination(destination: str) -> str:
  try:
    safe_destination = validate_relative_output_path(destination)
  except CompilerError as exc:
    raise DotagentsError(str(exc)) from exc
  if not safe_destination.startswith(".agents/"):
    raise DotagentsError(f"compiled artifact must be under .agents: {safe_destination}")
  return safe_destination


def compiled_staleness_messages(repo_root: Path) -> list[str]:
  manifest_path = repo_root / BUILD_MANIFEST_DESTINATION
  if not manifest_path.exists():
    return []
  try:
    build_manifest = read_build_manifest(manifest_path)
  except CompilerError as exc:
    return [f"compiled artifacts: build manifest error: {exc}"]

  messages: list[str] = []
  for source in build_manifest.sources:
    message = compiled_source_staleness_message(repo_root, source)
    if message:
      messages.append(message)
  return messages


def compiled_group_statuses(repo_root: Path) -> tuple[CompiledGroupStatus, ...]:
  manifest_path = repo_root / BUILD_MANIFEST_DESTINATION
  if not manifest_path.exists():
    return (CompiledGroupStatus("compiled artifacts", "ok", ("no compiled artifacts",)),)
  try:
    build_manifest = read_build_manifest(manifest_path)
  except CompilerError as exc:
    return (
      CompiledGroupStatus(
        "compiled artifacts",
        "invalid",
        (f"compiled artifacts: build manifest error: {exc}",),
      ),
    )

  groups = build_manifest.groups or (
    BuildGroup(
      id="compiled artifacts",
      compiler="unknown",
      output_prefix=".agents",
      artifacts=build_manifest.artifacts,
      sources=build_manifest.sources,
    ),
  )
  return tuple(compiled_group_status(repo_root, group) for group in groups)


def capability_index(repo_root: Path) -> CapabilityIndex:
  packaged_skills = packaged_capability_skills(repo_root)
  compiled_groups = capability_compiled_groups(repo_root)
  compiled_skills = tuple(
    compiled_capability_skill(group) for group in compiled_groups if group.id.startswith("skill:")
  )
  return CapabilityIndex(
    schema_version=CAPABILITY_INDEX_SCHEMA_VERSION,
    skills=packaged_skills + compiled_skills,
    compiled_groups=compiled_groups,
  )


def packaged_capability_skills(repo_root: Path) -> tuple[CapabilitySkill, ...]:
  lock_path = repo_root / ".agents" / "dotagents.lock"
  if not lock_path.exists():
    return ()
  runtime_lock = read_lock(lock_path)
  skills = runtime_lock.skills or ()
  capability_skills: list[CapabilitySkill] = []
  for skill in skills:
    path = f".agents/skills/{skill}"
    status: Literal["ok", "missing"] = "ok" if (repo_root / path).is_dir() else "missing"
    messages = () if status == "ok" else (f"skill missing: {path}",)
    capability_skills.append(
      CapabilitySkill(
        name=skill,
        kind="packaged",
        path=path,
        status=status,
        messages=messages,
      )
    )
  return tuple(capability_skills)


def capability_compiled_groups(repo_root: Path) -> tuple[CapabilityGroup, ...]:
  manifest_path = repo_root / BUILD_MANIFEST_DESTINATION
  if not manifest_path.exists():
    return (compiled_artifacts_capability_group("ok", "no compiled artifacts"),)
  try:
    build_manifest = read_build_manifest(manifest_path)
  except CompilerError as exc:
    message = f"compiled artifacts: build manifest error: {exc}"
    return (compiled_artifacts_capability_group("invalid", message),)
  groups = build_manifest.groups or (
    BuildGroup(
      id="compiled artifacts",
      compiler="unknown",
      output_prefix=".agents",
      artifacts=build_manifest.artifacts,
      sources=build_manifest.sources,
    ),
  )
  return tuple(compiled_capability_group(repo_root, group) for group in groups)


def compiled_artifacts_capability_group(
  status: CapabilityStatus,
  message: str,
) -> CapabilityGroup:
  return CapabilityGroup(
    id="compiled artifacts",
    compiler="unknown",
    output_prefix="",
    status=status,
    messages=(message,),
  )


def compiled_capability_group(repo_root: Path, group: BuildGroup) -> CapabilityGroup:
  status = compiled_group_status(repo_root, group)
  return CapabilityGroup(
    id=group.id,
    compiler=group.compiler,
    output_prefix=group.output_prefix,
    status=status.status,
    messages=status.messages,
  )


def compiled_capability_skill(group: CapabilityGroup) -> CapabilitySkill:
  name = group.id.removeprefix("skill:")
  return CapabilitySkill(
    name=name,
    kind="compiled",
    path=group.output_prefix,
    status=group.status,
    group_id=group.id,
    compiler=group.compiler,
    messages=group.messages,
  )


def capability_index_payload(index: CapabilityIndex) -> dict[str, object]:
  return {
    "schema_version": index.schema_version,
    "skills": [capability_skill_payload(skill) for skill in index.skills],
    "compiled_groups": [capability_group_payload(group) for group in index.compiled_groups],
  }


def capability_skill_payload(skill: CapabilitySkill) -> dict[str, object]:
  payload: dict[str, object] = {
    "name": skill.name,
    "kind": skill.kind,
    "path": skill.path,
    "status": skill.status,
  }
  if skill.group_id is not None:
    payload["group_id"] = skill.group_id
  if skill.compiler is not None:
    payload["compiler"] = skill.compiler
  if skill.messages:
    payload["messages"] = list(skill.messages)
  return payload


def capability_group_payload(group: CapabilityGroup) -> dict[str, object]:
  return {
    "id": group.id,
    "compiler": group.compiler,
    "output_prefix": group.output_prefix,
    "status": group.status,
    "messages": list(group.messages),
  }


def compiled_group_status(repo_root: Path, group: BuildGroup) -> CompiledGroupStatus:
  messages: list[str] = []
  for artifact in group.artifacts:
    message = compiled_artifact_status_message(repo_root, artifact)
    if message:
      messages.append(message)
  for source in group.sources:
    message = compiled_source_staleness_message(repo_root, source)
    if message:
      messages.append(message)
  return CompiledGroupStatus(group.id, compiled_status_from_messages(messages), tuple(messages))


def compiled_artifact_status_message(
  repo_root: Path,
  artifact: BuildManifestEntry,
) -> str | None:
  try:
    destination = validate_compiled_artifact_destination(artifact.artifact)
  except DotagentsError as exc:
    return f"compiled artifacts invalid: {exc}"
  path = repo_root / destination
  if not path.is_file():
    return f"compiled artifact missing: {destination}"
  actual_sha256 = sha256_file(path)
  if actual_sha256 != artifact.sha256:
    return f"compiled artifact changed since build manifest: {destination}"
  return None


def compiled_status_from_messages(
  messages: list[str],
) -> CapabilityStatus:
  if not messages:
    return "ok"
  if any("invalid" in message or "error" in message for message in messages):
    return "invalid"
  if any("missing" in message for message in messages):
    return "missing"
  return "stale"


def compiled_source_staleness_message(repo_root: Path, source: BuildSource) -> str | None:
  if source.kind == "file":
    try:
      reference = validate_relative_output_path(source.reference)
    except CompilerError as exc:
      return f"compiled artifacts stale: {exc}"
    return compiled_path_staleness(
      repo_root,
      reference,
      source.version,
      missing_label="file source",
      hash_label="file",
      changed_label="file source",
    )
  if source.kind == "package":
    if source.reference == "dotagents" and source.version != package_version():
      return "compiled artifacts stale: dotagents package changed"
    return None
  if source.kind == "variables":
    return None
  if source.kind in {"mcp", "mcp-command", "github-skill"}:
    return None
  if source.kind == "mcp-metadata":
    try:
      _, _, reference = parse_mcp_metadata_reference(source.reference)
      reference = validate_relative_output_path(reference)
    except CompilerError as exc:
      return f"compiled artifacts stale: {exc}"
    return compiled_path_staleness(
      repo_root,
      reference,
      source.version,
      missing_label="MCP metadata source",
      hash_label="MCP metadata source",
      changed_label="MCP metadata source",
    )
  if source.kind == "template":
    return compiled_file_like_source_staleness(repo_root, source, "template source")
  if source.kind == "template-variables":
    return compiled_file_like_source_staleness(repo_root, source, "template variables")
  return f"compiled artifacts stale: unrecognized source kind: {source.kind}"


def compiled_file_like_source_staleness(
  repo_root: Path,
  source: BuildSource,
  label: str,
) -> str | None:
  try:
    _, reference = parse_template_source_reference(source.reference)
    if reference == "<inline>":
      return None
    reference = validate_relative_output_path(reference)
  except CompilerError as exc:
    return f"compiled artifacts stale: {exc}"
  return compiled_path_staleness(
    repo_root,
    reference,
    source.version,
    missing_label=label,
    hash_label=label,
    changed_label=label,
  )


def compiled_path_staleness(
  repo_root: Path,
  reference: str,
  expected_version: str,
  missing_label: str,
  hash_label: str,
  changed_label: str,
) -> str | None:
  path = repo_root / reference
  if not path.is_file():
    return f"compiled artifacts stale: {missing_label} missing: {reference}"
  try:
    current_version = sha256_file(path)
  except OSError as exc:
    return f"compiled artifacts stale: cannot hash {hash_label}: {reference}: {exc}"
  if current_version != expected_version:
    return f"compiled artifacts stale: {changed_label} changed: {reference}"
  return None


def remove_stale_links(
  repo_root: Path,
  previous_lock: RuntimeLock | None,
  locked_links: list[LockedLink],
  operation_log: OperationLog,
) -> list[LockedLink]:
  if previous_lock is None:
    return []

  current_destinations = {link.destination for link in locked_links}
  skipped_links: list[LockedLink] = []
  prune_candidates: set[Path] = set()
  for link in previous_lock.links:
    if link.destination in current_destinations:
      continue
    destination = repo_root / link.destination
    if not remove_link_with_backup(repo_root, link, destination, operation_log):
      skipped_links.append(link)
    collect_parents(repo_root, destination, prune_candidates)

  prune_empty_dirs(repo_root, prune_candidates, operation_log)
  return skipped_links


def remove_stale_assets(
  repo_root: Path,
  previous_lock: RuntimeLock | None,
  locked_assets: list[LockedAsset],
  operation_log: OperationLog,
) -> list[LockedAsset]:
  if previous_lock is None:
    return []

  current_destinations = {asset.destination for asset in locked_assets}
  skipped_assets: list[LockedAsset] = []
  prune_candidates: set[Path] = set()
  for asset in previous_lock.assets:
    if asset.destination in current_destinations:
      continue
    destination = repo_root / asset.destination
    if not remove_locked_asset(repo_root, destination, asset.sha256, operation_log):
      skipped_assets.append(asset)
    collect_parents(repo_root, destination, prune_candidates)
  prune_empty_dirs(repo_root, prune_candidates, operation_log)
  return skipped_assets


def runtime_destination(runtime_dir: Path, entry: SyncEntry) -> Path:
  if entry.source == "skills":
    return runtime_dir / "skills"
  source = Path(entry.source)
  first = source.parts[0]
  if first in {"scripts", "skills", "hooks"}:
    return runtime_dir / source
  if entry.provider and first == entry.provider:
    suffix = Path(*source.parts[1:]) if len(source.parts) > 1 else Path()
    return runtime_dir / "providers" / entry.provider / suffix
  raise DotagentsError(f"unsupported manifest source root: {entry.source}")


def render_rules(
  runtime_context: RuntimeContext,
  operation_log: OperationLog,
  known_backup: BackupRecord | None = None,
) -> BackupRecord | None:
  """Write `.rules` and return the backup record from `write_text`, if any.

  Raises:
    DotagentsError: if the bundled `rules/rules.md` can't be read, or (via `write_text`)
      if `.rules` is a symlink or a `.rules.bak` conflict already exists.
  """
  shared_rules = runtime_context.asset_root / "rules" / "rules.md"
  try:
    shared = shared_rules.read_text(encoding="utf-8").rstrip()
  except OSError as exc:
    raise DotagentsError(f"cannot read bundled rules file: {shared_rules}") from exc
  chunks = ["<!-- Shared agent rules from dotagents package rules/rules.md -->", "", shared]
  local = runtime_context.repo_root / ".rules.local"
  if local.exists():
    chunks.extend(
      [
        "",
        "",
        "<!-- Local repo rules from .rules.local -->",
        "",
        local.read_text(encoding="utf-8").rstrip(),
      ]
    )
  return write_text(
    runtime_context.repo_root,
    runtime_context.repo_root / ".rules",
    "\n".join(chunks) + "\n",
    operation_log,
    backup_existing=runtime_context.is_global,
    known_backup=known_backup,
  )


def lock_entries(
  repo_root: Path, source: Path, destination: Path, source_name: str
) -> list[LockedAsset]:
  if source.is_file():
    return [LockedAsset(source_name, relative(repo_root, destination), sha256_file(source))]

  entries: list[LockedAsset] = []
  for path in sorted(source.rglob("*")):
    if path.is_file():
      relative_path = path.relative_to(source)
      entries.append(
        LockedAsset(
          str(Path(source_name) / relative_path),
          relative(repo_root, destination / relative_path),
          sha256_file(path),
        )
      )
  return entries


def unique_locked_assets(locked_assets: list[LockedAsset]) -> list[LockedAsset]:
  unique: dict[tuple[str, str], LockedAsset] = {}
  for asset in locked_assets:
    unique[(asset.source, asset.destination)] = asset
  return list(unique.values())


def validate_locked_asset_destinations_unique(locked_assets: list[LockedAsset]) -> None:
  assets_by_destination: dict[str, LockedAsset] = {}
  for asset in locked_assets:
    existing = assets_by_destination.get(asset.destination)
    if existing is not None and existing.source != asset.source:
      raise DotagentsError(
        "managed asset destination collision: "
        f"{asset.destination} from {existing.source} and {asset.source}"
      )
    assets_by_destination[asset.destination] = asset


def unique_locked_links(locked_links: list[LockedLink]) -> list[LockedLink]:
  unique: dict[str, LockedLink] = {}
  for link in locked_links:
    unique[link.destination] = link
  return list(unique.values())


def copy_path(
  repo_root: Path, source: Path, destination: Path, operation_log: OperationLog
) -> None:
  if source.is_dir():
    for path in sorted(source.rglob("*")):
      if path.is_file():
        copy_file(repo_root, path, destination / path.relative_to(source), operation_log)
    return
  copy_file(repo_root, source, destination, operation_log)


def copy_file(
  repo_root: Path, source: Path, destination: Path, operation_log: OperationLog
) -> None:
  resolve_parent_within_root(repo_root, destination)
  if destination.is_symlink():
    raise DotagentsError(
      f"refusing to replace symlink with managed file: {relative(repo_root, destination)}"
    )
  if (
    destination.exists()
    and destination.is_file()
    and filecmp.cmp(source, destination, shallow=False)
  ):
    operation_log.add(f"ok {relative(repo_root, destination)}")
    return
  if operation_log.dry_run:
    operation_log.add(f"would copy {relative(repo_root, destination)}")
    return
  destination.parent.mkdir(parents=True, exist_ok=True)
  shutil.copy2(source, destination)
  operation_log.add(f"copied {relative(repo_root, destination)}")


def migrate_legacy_backup(
  repo_root: Path, known_backup: BackupRecord | None, backup_path: Path
) -> BackupRecord | None:
  """Upgrade a fingerprint-less backup record (carried forward from a v1 lock) to a real
  fingerprint computed from `backup_path`'s current on-disk state, or drop it if the backup
  is no longer a readable file or symlink.

  Without this, carrying `known_backup.fingerprint = None` forward unchanged into a
  freshly-written v2 lock would record `backup` with no `backup_fingerprint` — unreadable
  by the next `read_lock` call, which requires a fingerprint whenever a v2 lock has a backup.
  """
  if known_backup is None or known_backup.fingerprint is not None:
    return known_backup
  resolve_parent_within_root(repo_root, backup_path)
  if backup_path.is_symlink() or backup_path.is_file() or backup_path.is_dir():
    return BackupRecord(known_backup.path, backup_fingerprint(backup_path))
  return None


def migrate_legacy_link_backup(repo_root: Path, link: LockedLink) -> LockedLink:
  """Return `link` with its backup fingerprint migrated if it's a legacy (fingerprint-less)
  record, so writing it back into a v2 lock doesn't produce an unreadable entry.

  Needed anywhere a `LockedLink` read from an existing lock is written back out without
  going through `link_path` (which already migrates via `migrate_legacy_backup`) — e.g.
  `remove_provider`, which carries forward links it isn't touching.
  """
  if link.backup is None or link.backup_fingerprint is not None:
    return link
  migrated = migrate_legacy_backup(
    repo_root, BackupRecord(link.backup, link.backup_fingerprint), repo_root / link.backup
  )
  return LockedLink(
    destination=link.destination,
    target=link.target,
    provider=link.provider,
    backup=migrated.path if migrated else None,
    backup_fingerprint=migrated.fingerprint if migrated else None,
  )


def write_text(
  repo_root: Path,
  destination: Path,
  content: str,
  operation_log: OperationLog,
  backup_existing: bool = False,
  known_backup: BackupRecord | None = None,
) -> BackupRecord | None:
  """Return the backup record for `destination` if one was created or already tracked, else None.

  `known_backup` is the backup previously recorded in the lock, if any. A `.bak` file found
  on disk is only ever reported back if it was created by this call or was already tracked —
  an unrelated pre-existing `.bak` file is never adopted as dotagents-owned.

  Raises:
    DotagentsError: if `destination` is a symlink, or if a `.bak` file already exists at the
      backup path (conflict must be resolved manually).
  """
  backup = destination.parent / (destination.name + ".bak")
  resolve_parent_within_root(repo_root, destination)
  known_backup = migrate_legacy_backup(repo_root, known_backup, backup)
  if destination.is_symlink():
    raise DotagentsError(
      f"refusing to replace symlink with managed file: {relative(repo_root, destination)}"
    )
  if (
    destination.exists()
    and destination.is_file()
    and destination.read_text(encoding="utf-8") == content
  ):
    operation_log.add(f"ok {relative(repo_root, destination)}")
    return known_backup
  backup_record = known_backup
  backup_rel = relative(repo_root, backup)
  already_tracked = known_backup is not None and known_backup.path == backup_rel
  if backup_existing and destination.exists() and not already_tracked:
    if backup.exists(follow_symlinks=False):
      raise DotagentsError(f"backup already exists: {backup_rel}; resolve manually and re-run")
    backup_record = BackupRecord(backup_rel, backup_fingerprint(destination))
    if operation_log.dry_run:
      operation_log.add(f"{WOULD_BACK_UP_PREFIX}{relative(repo_root, destination)} -> {backup_rel}")
      operation_log.planned_backups.append((destination, backup))
    else:
      destination.rename(backup)
      operation_log.add(f"backed up {relative(repo_root, destination)} -> {backup_rel}")
      operation_log.created_backups.append((destination, backup))
  if operation_log.dry_run:
    operation_log.add(f"would write {relative(repo_root, destination)}")
    return backup_record
  destination.write_text(content, encoding="utf-8")
  operation_log.add(f"wrote {relative(repo_root, destination)}")
  return backup_record


def link_path(
  repo_root: Path,
  source: Path,
  destination: Path,
  operation_log: OperationLog,
  known_backup: BackupRecord | None = None,
) -> BackupRecord | None:
  """Return the backup record for `destination` if one was created or already tracked, else None.

  `known_backup` is the backup previously recorded in the lock, if any. A `.bak` file found
  on disk is only ever reported back if it was created by this call or was already tracked —
  an unrelated pre-existing `.bak` file is never adopted as dotagents-owned.

  Raises:
    DotagentsError: if a `.bak` file already exists at the backup path (conflict must be resolved manually).
  """
  resolve_parent_within_root(repo_root, destination)
  backup = destination.parent / (destination.name + ".bak")
  target = os.path.relpath(source, destination.parent)
  already_linked = destination.is_symlink() and os.readlink(destination) == target

  # follow_symlinks=False: a pre-existing entry that isn't already our link — a
  # regular file, a symlink to something else, or a broken symlink — must be
  # backed up before replacement, not silently overwritten.
  if destination.exists(follow_symlinks=False) and not already_linked:
    if backup.exists(follow_symlinks=False):
      raise DotagentsError(
        f"backup already exists: {relative(repo_root, backup)}; resolve manually and re-run"
      )
    backup_record: BackupRecord | None = BackupRecord(
      relative(repo_root, backup), backup_fingerprint(destination)
    )
    if operation_log.dry_run:
      operation_log.add(
        f"{WOULD_BACK_UP_PREFIX}{relative(repo_root, destination)} -> {relative(repo_root, backup)}"
      )
      operation_log.planned_backups.append((destination, backup))
    else:
      destination.rename(backup)
      operation_log.add(
        f"backed up {relative(repo_root, destination)} -> {relative(repo_root, backup)}"
      )
      operation_log.created_backups.append((destination, backup))
  else:
    backup_record = migrate_legacy_backup(repo_root, known_backup, backup)

  if already_linked:
    operation_log.add(f"ok {relative(repo_root, destination)}")
    return backup_record

  if operation_log.dry_run:
    operation_log.add(f"would link {relative(repo_root, destination)} -> {target}")
    return backup_record

  destination.parent.mkdir(parents=True, exist_ok=True)
  if destination.exists() or destination.is_symlink():
    destination.unlink()
  destination.symlink_to(target)
  operation_log.add(f"linked {relative(repo_root, destination)} -> {target}")
  return backup_record


def ensure_dir(repo_root: Path, path: Path, operation_log: OperationLog) -> None:
  if path.exists():
    if not path.is_dir():
      raise DotagentsError(f"expected directory: {relative(repo_root, path)}")
    return
  if operation_log.dry_run:
    operation_log.add(f"would create {relative(repo_root, path)}")
    return
  path.mkdir(parents=True)
  operation_log.add(f"created {relative(repo_root, path)}")


def resolve_within_root(repo_root: Path, path: Path) -> Path:
  """Resolve `path` and confirm it stays within `repo_root`, following any symlinked parents.

  Lockfile-sourced destinations are validated lexically at parse time
  (`validate_contained_relative_path`), but that catches only `..`/absolute-path strings —
  not an intermediate directory that is itself a symlink pointing outside root. This closes
  that gap at the point of actual filesystem use.

  Raises:
    DotagentsError: if `path` resolves outside `repo_root`.
  """
  resolved = path.resolve()
  if not resolved.is_relative_to(repo_root.resolve()):
    raise DotagentsError(f"path escapes root via symlink: {relative(repo_root, path)}")
  return resolved


def resolve_parent_within_root(repo_root: Path, path: Path) -> None:
  """Confirm `path`'s parent directory chain stays within `repo_root`, without resolving `path`.

  For operations that rename or unlink a symlink entry directly (never open or follow it) —
  `resolve_within_root` would incorrectly reject a legitimate symlink whose own target lies
  outside root (e.g. a backed-up `CLAUDE.md -> ~/notes.md`), since `Path.resolve()` dereferences
  the final path component too, not just its parents.

  Raises:
    DotagentsError: if `path`'s parent directory resolves outside `repo_root`.
  """
  resolved_parent = path.parent.resolve()
  if not resolved_parent.is_relative_to(repo_root.resolve()):
    raise DotagentsError(f"path escapes root via symlink: {relative(repo_root, path)}")


def remove_locked_link(
  repo_root: Path, destination: Path, expected_target: str, operation_log: OperationLog
) -> bool:
  """Return True if the link was removed (or would be in dry-run), False if skipped.

  Raises:
    DotagentsError: if `destination`'s parent directory resolves outside `repo_root`.
  """
  resolve_parent_within_root(repo_root, destination)
  display = relative(repo_root, destination)
  if not destination.exists() and not destination.is_symlink():
    operation_log.add(f"missing {display}")
    return True
  if not destination.is_symlink():
    operation_log.add(f"skip user-owned {display}; remove manually after verifying")
    return False

  actual_target = os.readlink(destination)
  if actual_target != expected_target:
    operation_log.add(f"skip unexpected symlink {display}; remove manually after verifying")
    return False

  if operation_log.dry_run:
    operation_log.add(f"would remove {display}")
    operation_log.pending_removals.add(destination)
    return True
  destination.unlink()
  operation_log.add(f"removed {display}")
  return True


def restore_backup(
  repo_root: Path,
  backup_path: Path,
  destination: Path,
  operation_log: OperationLog,
  expected_fingerprint: str | None = None,
) -> None:
  """Rename `backup_path` onto `destination`.

  Skips (with a log entry, no exception) if the backup is missing, not a regular file,
  directory, or symlink, or its fingerprint doesn't match `expected_fingerprint`.

  Raises:
    DotagentsError: if `backup_path` or `destination`'s parent directory resolves outside
      `repo_root`.
  """
  resolve_parent_within_root(repo_root, backup_path)
  resolve_parent_within_root(repo_root, destination)
  if not backup_path.exists(follow_symlinks=False):
    operation_log.add(f"backup missing {relative(repo_root, backup_path)}; skipped restore")
    return
  if not backup_path.is_symlink() and not backup_path.is_file():
    if (
      backup_path.is_dir()
      and expected_fingerprint
      and expected_fingerprint.startswith("directory:")
    ):
      pass
    else:
      # A directory or FIFO at the backup path — swapped in after backup creation, or a
      # legacy backup with no fingerprint to check. Never rename an untrusted non-regular
      # entry onto a managed destination, and never let backup_fingerprint() below open it
      # (IsADirectoryError, or a hang on a FIFO with no writer).
      operation_log.add(
        f"backup is not a file or symlink {relative(repo_root, backup_path)}; "
        "skipped restore, resolve manually"
      )
      return

  def fingerprint_mismatch() -> bool:
    return (
      expected_fingerprint is not None and backup_fingerprint(backup_path) != expected_fingerprint
    )

  if fingerprint_mismatch():
    operation_log.add(
      f"backup fingerprint mismatch {relative(repo_root, backup_path)}; "
      "skipped restore, resolve manually"
    )
    return
  if operation_log.dry_run:
    operation_log.add(
      f"would restore {relative(repo_root, backup_path)} -> {relative(repo_root, destination)}"
    )
    return
  # Re-verify immediately before the mutation. Directory fingerprinting requires a full
  # recursive walk, which widens the window between "checked" and "renamed" compared to a
  # single file's hash — this doesn't eliminate the race (no OS-level atomicity is used, and
  # the same race exists between this check and the rename call below), but shrinks it to
  # the minimum achievable without one.
  if fingerprint_mismatch():
    operation_log.add(
      f"backup fingerprint mismatch {relative(repo_root, backup_path)}; "
      "skipped restore, resolve manually"
    )
    return
  backup_path.rename(destination)
  operation_log.add(
    f"restored {relative(repo_root, backup_path)} -> {relative(repo_root, destination)}"
  )


def remove_link_with_backup(
  repo_root: Path, link: LockedLink, destination: Path, operation_log: OperationLog
) -> bool:
  """Remove a locked link and restore its backup on success. Return whether it was removed.

  Raises:
    DotagentsError: if `destination` or the link's backup's parent directory resolves
      outside `repo_root`.
  """
  removed = remove_locked_link(repo_root, destination, link.target, operation_log)
  if removed and link.backup:
    restore_backup(
      repo_root, repo_root / link.backup, destination, operation_log, link.backup_fingerprint
    )
  return removed


def remove_locked_asset(
  repo_root: Path, path: Path, expected_sha256: str, operation_log: OperationLog
) -> bool:
  """Return True if the asset was removed (or would be in dry-run), False if skipped.

  Raises:
    DotagentsError: if `path` resolves outside `repo_root`.
  """
  resolve_parent_within_root(repo_root, path)
  display = relative(repo_root, path)
  if not path.exists() and not path.is_symlink():
    operation_log.add(f"missing {display}")
    return True
  if path.is_symlink() or not path.is_file():
    operation_log.add(f"skip unexpected {display}; remove manually after verifying")
    return False
  if sha256_file(path) != expected_sha256:
    operation_log.add(f"skip changed {display}; remove manually after verifying")
    return False

  if operation_log.dry_run:
    operation_log.add(f"would remove {display}")
    operation_log.pending_removals.add(path)
    return True
  path.unlink()
  operation_log.add(f"removed {display}")
  return True


def remove_generated_rules(
  repo_root: Path,
  operation_log: OperationLog,
  rules_backup: str | None,
  rules_backup_fingerprint: str | None = None,
) -> None:
  """Remove a dotagents-generated `.rules` and restore `rules_backup`, if any.

  Skips (with a log entry, no exception) if `.rules` is missing, unexpected, unreadable, or
  user-owned (no dotagents marker comment).

  Raises:
    DotagentsError: if (via `restore_backup`) `rules_backup` resolves outside `repo_root`.
  """
  rules = repo_root / ".rules"
  display = relative(repo_root, rules)
  if not rules.exists() and not rules.is_symlink():
    operation_log.add(f"missing {display}")
    if rules_backup:
      restore_backup(
        repo_root, repo_root / rules_backup, rules, operation_log, rules_backup_fingerprint
      )
    return
  if rules.is_symlink() or not rules.is_file():
    operation_log.add(f"skip unexpected {display}; remove manually after verifying")
    return
  try:
    content = rules.read_text(encoding="utf-8")
  except OSError:
    operation_log.add(f"skip unreadable {display}; remove manually after verifying")
    return
  if "<!-- Shared agent rules from dotagents package rules/rules.md -->" not in content:
    operation_log.add(f"skip user-owned {display}; remove manually after verifying")
    return

  if operation_log.dry_run:
    operation_log.add(f"would remove {display}")
    operation_log.pending_removals.add(rules)
  else:
    rules.unlink()
    operation_log.add(f"removed {display}")

  if rules_backup:
    restore_backup(
      repo_root, repo_root / rules_backup, rules, operation_log, rules_backup_fingerprint
    )


def remove_lockfile(repo_root: Path, lock_path: Path, operation_log: OperationLog) -> None:
  display = relative(repo_root, lock_path)
  if not lock_path.exists():
    operation_log.add(f"missing {display}")
    return
  if not lock_path.is_file():
    operation_log.add(f"skip unexpected {display}; remove manually after verifying")
    return

  if operation_log.dry_run:
    operation_log.add(f"would remove {display}")
    operation_log.pending_removals.add(lock_path)
    return
  lock_path.unlink()
  operation_log.add(f"removed {display}")


def collect_parents(repo_root: Path, path: Path, candidates: set[Path]) -> None:
  current = path.parent
  while current != repo_root and repo_root in current.parents:
    candidates.add(current)
    current = current.parent


def prune_empty_dirs(repo_root: Path, candidates: set[Path], operation_log: OperationLog) -> None:
  for path in sorted(candidates, key=lambda item: len(item.parts), reverse=True):
    if path == repo_root or not path.exists() or not path.is_dir():
      continue
    display = relative(repo_root, path)
    if operation_log.dry_run:
      remaining = [child for child in path.iterdir() if child not in operation_log.pending_removals]
      if not remaining:
        operation_log.add(f"would remove empty {display}")
        operation_log.pending_removals.add(path)
    else:
      try:
        next(path.iterdir())
      except StopIteration:
        path.rmdir()
        operation_log.add(f"removed empty {display}")


def relative(base: Path, path: Path) -> str:
  try:
    return os.path.relpath(path, base)
  except ValueError:
    return str(path)
